
import { Vocabulary } from './types';

export const LESSON_TITLES: Record<number, string> = {
  1: "Chào hỏi - Giới thiệu",
  2: "Vật dụng xung quanh",
  3: "Địa điểm - Nơi chốn",
  4: "Thời gian - Ngày giờ",
  5: "Di chuyển - Đi lại",
  6: "Hành động - Ăn uống",
  7: "Công cụ - Cách thức",
  8: "Tính từ - Miêu tả",
  9: "Sở thích - Khả năng",
  10: "Sự hiện diện - Có gì",
  11: "Số lượng - Cách đếm",
  12: "Quá khứ - So sánh",
  13: "Mong muốn - Dự định",
  14: "Yêu cầu - Thể Te",
  15: "Cho phép - Cấm đoán",
  16: "Trình tự hành động",
  17: "Nghĩa vụ - Thể Nai",
  18: "Khả năng - Thể Từ điển",
  19: "Kinh nghiệm - Thể Ta",
  20: "Thể thông thường",
  21: "Ý kiến - Phán đoán",
  22: "Mệnh đề bổ ngữ",
  23: "Thời điểm - Khi nào",
  24: "Cho nhận - Biếu tặng",
  25: "Điều kiện - Giả định"
};

export const INITIAL_VOCAB: Vocabulary[] = [
  // --- BÀI 1 ---
  { id: 'l1-1', kanji: "私", reading: "わたし", meaning: "tôi", category: 'kanji', lesson: 1 },
  { id: 'l1-2', kanji: "あなた", reading: "あなた", meaning: "anh/chị, ông/bà, bạn (ngôi thứ II số ít)", category: 'general', lesson: 1 },
  { id: 'l1-3', kanji: "あの人", reading: "あのひと", meaning: "người kia, người đó", category: 'kanji', lesson: 1 },
  { id: 'l1-4', kanji: "あの方", reading: "あのかた", meaning: "vị kia (cách nói lịch sự của \"ano hito\")", category: 'kanji', lesson: 1 },
  { id: 'l1-5', kanji: "～さん", reading: "～さん", meaning: "anh, chị, ông, bà (hậu tố thêm sau tên)", category: 'general', lesson: 1 },
  { id: 'l1-6', kanji: "～ちゃん", reading: "～ちゃん", meaning: "hậu tố thêm sau tên trẻ em", category: 'general', lesson: 1 },
  { id: 'l1-7', kanji: "～人", reading: "～じん", meaning: "người (nước ~)", category: 'kanji', lesson: 1 },
  { id: 'l1-8', kanji: "先生", reading: "せんせい", meaning: "thầy/cô (không dùng khi giới thiệu nghề nghiệp của mình)", category: 'kanji', lesson: 1 },
  { id: 'l1-9', kanji: "教師", reading: "きょうし", meaning: "giáo viên", category: 'kanji', lesson: 1 },
  { id: 'l1-10', kanji: "学生", reading: "がくせい", meaning: "học sinh, sinh viên", category: 'kanji', lesson: 1 },
  { id: 'l1-11', kanji: "会社員", reading: "かいしゃいん", meaning: "nhân viên công ty", category: 'kanji', lesson: 1 },
  { id: 'l1-12', kanji: "社員", reading: "しゃいん", meaning: "nhân viên công ty (dùng kèm theo tên công ty)", category: 'kanji', lesson: 1 },
  { id: 'l1-13', kanji: "銀行員", reading: "ぎんこういん", meaning: " nhân viên ngân hàng", category: 'kanji', lesson: 1 },
  { id: 'l1-14', kanji: "医者", reading: "いしゃ", meaning: "bác sĩ", category: 'kanji', lesson: 1 },
  { id: 'l1-15', kanji: "研究者", reading: "けんゅうしゃ", meaning: "nhà nghiên cứu", category: 'kanji', lesson: 1 },
  { id: 'l1-16', kanji: "大学", reading: "だいがく", meaning: "đại học, trường đại học", category: 'kanji', lesson: 1 },
  { id: 'l1-17', kanji: "病院", reading: "びょういん", meaning: "bệnh viện", category: 'kanji', lesson: 1 },
  { id: 'l1-18', kanji: "誰", reading: "だれ", meaning: "ai", category: 'kanji', lesson: 1 },
  { id: 'l1-19', kanji: "どなた", reading: "どなた", meaning: "vị nào (cách nói lịch sự của \"dare\")", category: 'general', lesson: 1 },
  { id: 'l1-20', kanji: "～歳", reading: "～さい", meaning: "～ tuổi", category: 'kanji', lesson: 1 },
  { id: 'l1-21', kanji: "何歳", reading: "なんさい", meaning: "mấy tuổi, bao nhiêu tuổi", category: 'kanji', lesson: 1 },
  { id: 'l1-22', kanji: "おいくつ", reading: "おいくつ", meaning: "bao nhiêu tuổi (cách nói lịch sự của \"nansai\")", category: 'general', lesson: 1 },
  { id: 'l1-23', kanji: "はい", reading: "はい", meaning: "vâng, dạ", category: 'general', lesson: 1 },
  { id: 'l1-24', kanji: "いいえ", reading: "いいえ", meaning: "không", category: 'general', lesson: 1 },
  { id: 'l1-c1', kanji: "初めまして", reading: "はじめまして", meaning: "Rất hân hạnh được gặp anh/chị. (Lời chào lần đầu gặp mặt)", category: 'general', lesson: 1 },
  { id: 'l1-c2', kanji: "～から 来ました", reading: "～から きました", meaning: "Tôi đến từ ～.", category: 'kanji', lesson: 1 },
  { id: 'l1-c3', kanji: "[どうぞ] よろしく [お願いします]", reading: "よろしく おねがいします", meaning: "Rất vui được làm quen với anh/chị. (Rất mong nhận được sự giúp đỡ)", category: 'kanji', lesson: 1 },
  { id: 'l1-c4', kanji: "失礼ですが", reading: "しつれいですが", meaning: "Xin lỗi... (dùng khi hỏi thông tin cá nhân)", category: 'kanji', lesson: 1 },
  { id: 'l1-c5', kanji: "お名前は？", reading: "おなまえは？", meaning: "Tên anh/chị là gì?", category: 'kanji', lesson: 1 },
  { id: 'l1-c6', kanji: "こちらは ～さんです", reading: "こちらは ～さんです", meaning: "Đây là anh/chị/ông/bà ～.", category: 'general', lesson: 1 },

  // --- BÀI 2 ---
  { id: 'l2-1', kanji: "これ", reading: "これ", meaning: "cái này, đây (vật ở gần người nói)", category: 'general', lesson: 2 },
  { id: 'l2-2', kanji: "それ", reading: "それ", meaning: "cái đó, đó (vật ở gần người nghe)", category: 'general', lesson: 2 },
  { id: 'l2-3', kanji: "あれ", reading: "あれ", meaning: "cái kia, kia (vật ở xa cả hai)", category: 'general', lesson: 2 },
  { id: 'l2-4', kanji: "この～", reading: "この～", meaning: "~ này (gần người nói)", category: 'general', lesson: 2 },
  { id: 'l2-5', kanji: "その～", reading: "その～", meaning: "~ đó (gần người nghe)", category: 'general', lesson: 2 },
  { id: 'l2-6', kanji: "あの～", reading: "あの～", meaning: "~ kia (xa cả hai)", category: 'general', lesson: 2 },
  { id: 'l2-7', kanji: "本", reading: "ほん", meaning: "sách", category: 'kanji', lesson: 2 },
  { id: 'l2-8', kanji: "辞書", reading: "じしょ", meaning: "từ điển", category: 'kanji', lesson: 2 },
  { id: 'l2-9', kanji: "雑誌", reading: "ざっし", meaning: "tạp chí", category: 'kanji', lesson: 2 },
  { id: 'l2-10', kanji: "新聞", reading: "しんぶん", meaning: "báo", category: 'kanji', lesson: 2 },
  { id: 'l2-11', kanji: "ノート", reading: "ノート", meaning: "vở", category: 'general', lesson: 2 },
  { id: 'l2-12', kanji: "手帳", reading: "てちょう", meaning: "sổ tay", category: 'kanji', lesson: 2 },
  { id: 'l2-13', kanji: "名刺", reading: "めいし", meaning: "danh thiếp", category: 'kanji', lesson: 2 },
  { id: 'l2-14', kanji: "カード", reading: "カード", meaning: "thẻ, các, cạc", category: 'general', lesson: 2 },
  { id: 'l2-15', kanji: "鉛筆", reading: "えんぴつ", meaning: "bút chì", category: 'kanji', lesson: 2 },
  { id: 'l2-16', kanji: "ボールペン", reading: "ボールペン", meaning: "bút bi", category: 'general', lesson: 2 },
  { id: 'l2-17', kanji: "シャープペンシル", reading: "シャープペンシル", meaning: "bút chì kim, bút chì bấm", category: 'general', lesson: 2 },
  { id: 'l2-18', kanji: "かぎ", reading: "かぎ", meaning: "chìa khóa", category: 'general', lesson: 2 },
  { id: 'l2-19', kanji: "時計", reading: "とけい", meaning: "đồng hồ", category: 'kanji', lesson: 2 },
  { id: 'l2-20', kanji: "傘", reading: "かさ", meaning: "ô, dù", category: 'kanji', lesson: 2 },
  { id: 'l2-21', kanji: "かばん", reading: "かばん", meaning: "cặp sách, túi sách", category: 'general', lesson: 2 },
  { id: 'l2-22', kanji: "CD", reading: "CD", meaning: "đĩa CD", category: 'general', lesson: 2 },
  { id: 'l2-23', kanji: "テレビ", reading: "テレビ", meaning: "tivi", category: 'general', lesson: 2 },
  { id: 'l2-24', kanji: "ラジオ", reading: "ラジオ", meaning: "radio", category: 'general', lesson: 2 },
  { id: 'l2-25', kanji: "カメラ", reading: "カメラ", meaning: "máy ảnh", category: 'general', lesson: 2 },
  { id: 'l2-26', kanji: "コンピューター", reading: "コンピューター", meaning: "máy vi tính", category: 'general', lesson: 2 },
  { id: 'l2-27', kanji: "車", reading: "くるま", meaning: "ô tô, xe hơi", category: 'kanji', lesson: 2 },
  { id: 'l2-28', kanji: "机", reading: "つくえ", meaning: "bàn", category: 'kanji', lesson: 2 },
  { id: 'l2-29', kanji: "いす", reading: "いす", meaning: "ghế", category: 'general', lesson: 2 },
  { id: 'l2-30', kanji: "チョコレート", reading: "チョコレート", meaning: "sôcôla", category: 'general', lesson: 2 },
  { id: 'l2-31', kanji: "コーヒー", reading: "コーヒー", meaning: "cà phê", category: 'general', lesson: 2 },
  { id: 'l2-32', kanji: "[お]土産", reading: "[お]みやげ", meaning: "quà (mua khi đi xa về hoặc mang đi thăm)", category: 'kanji', lesson: 2 },
  { id: 'l2-33', kanji: "英語", reading: "えいご", meaning: "tiếng Anh", category: 'kanji', lesson: 2 },
  { id: 'l2-34', kanji: "日本語", reading: "にほんご", meaning: "tiếng Nhật", category: 'kanji', lesson: 2 },
  { id: 'l2-35', kanji: "～語", reading: "～ご", meaning: "tiếng ~", category: 'kanji', lesson: 2 },
  { id: 'l2-36', kanji: "何", reading: "なん", meaning: "cái gì, gì", category: 'kanji', lesson: 2 },
  { id: 'l2-37', kanji: "そう", reading: "そう", meaning: "đúng vậy, vậy", category: 'general', lesson: 2 },
  { id: 'l2-c1', kanji: "あのう", reading: "あのう", meaning: "à, ... (dùng khi ngập ngừng, do dự)", category: 'general', lesson: 2 },
  { id: 'l2-c2', kanji: "えっ", reading: "えっ", meaning: "Hả? (dùng khi ngạc nhiên)", category: 'general', lesson: 2 },
  { id: 'l2-c3', kanji: "どうぞ", reading: "どうぞ", meaning: "Xin mời.", category: 'general', lesson: 2 },
  { id: 'l2-c4', kanji: "[どうも] ありがとう [ございます]", reading: "ありがとう ございます", meaning: "Xin [chân thành] cám ơn.", category: 'general', lesson: 2 },
  { id: 'l2-c5', kanji: "そうですか", reading: "そうですか", meaning: "Thế à.", category: 'general', lesson: 2 },
  { id: 'l2-c6', kanji: "違います", reading: "ちがいます", meaning: "Không phải, không đúng, sai rồi.", category: 'verb', lesson: 2 },
  { id: 'l2-c7', kanji: "あ", reading: "あ", meaning: "A! / Ôi!", category: 'general', lesson: 2 },
  { id: 'l2-c8', kanji: "これから お世話になります", reading: "これから おせわになります", meaning: "Từ nay tôi rất mong được sự giúp đỡ của anh/chị.", category: 'kanji', lesson: 2 },
  { id: 'l2-c9', kanji: "こちらこそ [どうぞ] よろしく [お願いします]", reading: "こちらこそ よろしく おねがいします", meaning: "Chính tôi mới là người mong được sự giúp đỡ của anh/chị.", category: 'kanji', lesson: 2 },

  // --- BÀI 3 ---
  { id: 'l3-1', kanji: "教室", reading: "きょうしつ", meaning: "lớp học, phòng học", category: 'kanji', lesson: 3 },
  { id: 'l3-2', kanji: "食堂", reading: "しょくどう", meaning: "nhà ăn", category: 'kanji', lesson: 3 },
  { id: 'l3-3', kanji: "事務所", reading: "じむしょ", meaning: "văn phòng", category: 'kanji', lesson: 3 },
  { id: 'l3-4', kanji: "会議室", reading: "かいぎしつ", meaning: "phòng họp", category: 'kanji', lesson: 3 },
  { id: 'l3-5', kanji: "受付", reading: "うけつけ", meaning: "quầy lễ tân, phòng thường trực", category: 'kanji', lesson: 3 },
  { id: 'l3-6', kanji: "ロビー", reading: "ロビー", meaning: "hành lang, đại sảnh", category: 'general', lesson: 3 },
  { id: 'l3-7', kanji: "部屋", reading: "へや", meaning: "căn phòng", category: 'kanji', lesson: 3 },
  { id: 'l3-8', kanji: "トイレ (お手洗い)", reading: "トイレ (おてあらい)", meaning: "toa-lét, nhà vệ sinh", category: 'kanji', lesson: 3 },
  { id: 'l3-9', kanji: "階段", reading: "かいだん", meaning: "cầu thang", category: 'kanji', lesson: 3 },
  { id: 'l3-10', kanji: "エレベーター", reading: "エレベーター", meaning: "thang máy", category: 'general', lesson: 3 },
  { id: 'l3-11', kanji: "エスカレーター", reading: "エスカレーター", meaning: "thang cuốn", category: 'general', lesson: 3 },
  { id: 'l3-12', kanji: "[お]国", reading: "[お]くに", meaning: "nước (của anh/chị)", category: 'kanji', lesson: 3 },
  { id: 'l3-13', kanji: "会社", reading: "かいしゃ", meaning: "công ty", category: 'kanji', lesson: 3 },
  { id: 'l3-14', kanji: "うち", reading: "うち", meaning: "nhà", category: 'general', lesson: 3 },
  { id: 'l3-15', kanji: "電話", reading: "でんわ", meaning: "điện thoại", category: 'kanji', lesson: 3 },
  { id: 'l3-16', kanji: "靴", reading: "くつ", meaning: "giày", category: 'kanji', lesson: 3 },
  { id: 'l3-17', kanji: "ネクタイ", reading: "ネクタイ", meaning: "cà vạt", category: 'general', lesson: 3 },
  { id: 'l3-18', kanji: "ワイン", reading: "ワイン", meaning: "rượu vang", category: 'general', lesson: 3 },
  { id: 'l3-19', kanji: "タバコ", reading: "タバコ", meaning: "thuốc lá", category: 'general', lesson: 3 },
  { id: 'l3-20', kanji: "売り場", reading: "うりば", meaning: "quầy bán (trong bách hóa)", category: 'kanji', lesson: 3 },
  { id: 'l3-21', kanji: "地下", reading: "ちか", meaning: "tầng hầm, dưới mặt đất", category: 'kanji', lesson: 3 },
  { id: 'l3-22', kanji: "～階", reading: "～かい (～がい)", meaning: "tầng thứ ~", category: 'kanji', lesson: 3 },
  { id: 'l3-23', kanji: "何階", reading: "なんがい", meaning: "tầng mấy", category: 'kanji', lesson: 3 },
  { id: 'l3-24', kanji: "～円", reading: "～えん", meaning: "yên", category: 'kanji', lesson: 3 },
  { id: 'l3-25', kanji: "いくら", reading: "いくら", meaning: "bao nhiêu tiền", category: 'general', lesson: 3 },
  { id: 'l3-26', kanji: "百", reading: "ひゃく", meaning: "trăm", category: 'kanji', lesson: 3 },
  { id: 'l3-27', kanji: "千", reading: "せん", meaning: "nghìn", category: 'kanji', lesson: 3 },
  { id: 'l3-28', kanji: "万", reading: "まん", meaning: "mười nghìn, vạn", category: 'kanji', lesson: 3 },
  { id: 'l3-29', kanji: "自動販売機", reading: "じどうはんばいき", meaning: "máy bán hàng tự động", category: 'kanji', lesson: 3 },
  { id: 'l3-c1', kanji: "すみません", reading: "すみません", meaning: "Xin lỗi.", category: 'general', lesson: 3 },
  { id: 'l3-c2', kanji: "どうも", reading: "どうも", meaning: "Cám ơn.", category: 'general', lesson: 3 },
  { id: 'l3-c3', kanji: "いらっしゃいませ", reading: "いらっしゃいませ", meaning: "Xin chào quý khách, mời quý khách vào.", category: 'general', lesson: 3 },
  { id: 'l3-c4', kanji: "[～を] 見せてください", reading: "[～を] みせてください", meaning: "Cho tôi xem [～].", category: 'kanji', lesson: 3 },
  { id: 'l3-c5', kanji: "じゃ", reading: "じゃ", meaning: "Thế thì, vậy thì.", category: 'general', lesson: 3 },
  { id: 'l3-c6', kanji: "[～を] ください", reading: "[～を] ください", meaning: "Cho tôi [～].", category: 'general', lesson: 3 },

  // --- BÀI 4 ---
  { id: 'l4-1', kanji: "起きます", reading: "おきます", meaning: "dậy, thức dậy", category: 'verb', lesson: 4 },
  { id: 'l4-2', kanji: "寝ます", reading: "ねます", meaning: "ngủ, đi ngủ", category: 'verb', lesson: 4 },
  { id: 'l4-3', kanji: "働きます", reading: "はたらきます", meaning: "làm việc", category: 'verb', lesson: 4 },
  { id: 'l4-4', kanji: "休みます", reading: "やすみます", meaning: "nghỉ, nghỉ ngơi", category: 'verb', lesson: 4 },
  { id: 'l4-5', kanji: "勉強します", reading: "べんきょうします", meaning: "học", category: 'verb', lesson: 4 },
  { id: 'l4-6', kanji: "終わります", reading: "おわります", meaning: "hết, kết thúc, xong", category: 'verb', lesson: 4 },
  { id: 'l4-7', kanji: "デパート", reading: "デパート", meaning: "bách hóa", category: 'general', lesson: 4 },
  { id: 'l4-8', kanji: "銀行", reading: "ぎんこう", meaning: "ngân hàng", category: 'kanji', lesson: 4 },
  { id: 'l4-9', kanji: "郵便局", reading: "ゆうびんきょく", meaning: "bưu điện", category: 'kanji', lesson: 4 },
  { id: 'l4-10', kanji: "図書館", reading: "としょかん", meaning: "thư viện", category: 'kanji', lesson: 4 },
  { id: 'l4-11', kanji: "美術館", reading: "びじゅつかん", meaning: "bảo tàng mỹ thuật", category: 'kanji', lesson: 4 },
  { id: 'l4-12', kanji: "今", reading: "いま", meaning: "bây giờ", category: 'kanji', lesson: 4 },
  { id: 'l4-13', kanji: "～時", reading: "～じ", meaning: "～ giờ", category: 'kanji', lesson: 4 },
  { id: 'l4-14', kanji: "～分", reading: "～ふん（～ぷん）", meaning: "～ phút", category: 'kanji', lesson: 4 },
  { id: 'l4-15', kanji: "半", reading: "はん", meaning: "rưỡi, nửa", category: 'kanji', lesson: 4 },
  { id: 'l4-16', kanji: "何時", reading: "なんじ", meaning: "mấy giờ", category: 'kanji', lesson: 4 },
  { id: 'l4-17', kanji: "何分", reading: "なんぷん", meaning: "mấy phút", category: 'kanji', lesson: 4 },
  { id: 'l4-18', kanji: "午前", reading: "ごぜん", meaning: "sáng, trước 12 giờ trưa (AM)", category: 'kanji', lesson: 4 },
  { id: 'l4-19', kanji: "午後", reading: "ごご", meaning: "chiều, sau 12 giờ trưa (PM)", category: 'kanji', lesson: 4 },
  { id: 'l4-20', kanji: "朝", reading: "あさ", meaning: "buổi sáng, sáng", category: 'kanji', lesson: 4 },
  { id: 'l4-21', kanji: "昼", reading: "ひる", meaning: "buổi trưa, trưa", category: 'kanji', lesson: 4 },
  { id: 'l4-22', kanji: "晩（夜）", reading: "ばん（よる）", meaning: "buổi tối, tối", category: 'kanji', lesson: 4 },
  { id: 'l4-23', kanji: "昼休み", reading: "ひるやすみ", meaning: "nghỉ trưa", category: 'kanji', lesson: 4 },
  { id: 'l4-24', kanji: "おととい", reading: "おととい", meaning: "hôm kia", category: 'general', lesson: 4 },
  { id: 'l4-25', kanji: "きのう", reading: "きのう", meaning: "hôm qua", category: 'general', lesson: 4 },
  { id: 'l4-26', kanji: "きょう", reading: "きょう", meaning: "hôm nay", category: 'general', lesson: 4 },
  { id: 'l4-27', kanji: "あした", reading: "あした", meaning: "ngày mai", category: 'general', lesson: 4 },
  { id: 'l4-28', kanji: "あさって", reading: "あさって", meaning: "ngày kia", category: 'general', lesson: 4 },
  { id: 'l4-29', kanji: "けさ", reading: "けさ", meaning: "sáng nay", category: 'general', lesson: 4 },
  { id: 'l4-30', kanji: "今晩", reading: "こんばん", meaning: "tối nay", category: 'kanji', lesson: 4 },
  { id: 'l4-31', kanji: "休み", reading: "やすみ", meaning: "nghỉ, nghỉ phép, ngày nghỉ", category: 'kanji', lesson: 4 },
  { id: 'l4-32', kanji: "毎朝", reading: "まいあさ", meaning: "hàng sáng, mỗi sáng", category: 'kanji', lesson: 4 },
  { id: 'l4-33', kanji: "毎晩", reading: "まいばん", meaning: "hàng tối, mỗi tối", category: 'kanji', lesson: 4 },
  { id: 'l4-34', kanji: "毎日", reading: "まいにち", meaning: "hàng ngày, mỗi ngày", category: 'kanji', lesson: 4 },
  { id: 'l4-35', kanji: "月曜日", reading: "げつようび", meaning: "thứ hai", category: 'kanji', lesson: 4 },
  { id: 'l4-36', kanji: "火曜日", reading: "かようび", meaning: "thứ ba", category: 'kanji', lesson: 4 },
  { id: 'l4-37', kanji: "水曜日", reading: "すいようび", meaning: "thứ tư", category: 'kanji', lesson: 4 },
  { id: 'l4-38', kanji: "木曜日", reading: "もくようび", meaning: "thứ năm", category: 'kanji', lesson: 4 },
  { id: 'l4-39', kanji: "金曜日", reading: "きんようび", meaning: "thứ sáu", category: 'kanji', lesson: 4 },
  { id: 'l4-40', kanji: "土曜日", reading: "どようび", meaning: "thứ bảy", category: 'kanji', lesson: 4 },
  { id: 'l4-41', kanji: "日曜日", reading: "にちようび", meaning: "chủ nhật", category: 'kanji', lesson: 4 },
  { id: 'l4-42', kanji: "何曜日", reading: "なんようび", meaning: "thứ mấy", category: 'kanji', lesson: 4 },
  { id: 'l4-43', kanji: "番号", reading: "ばんごう", meaning: "số", category: 'kanji', lesson: 4 },
  { id: 'l4-44', kanji: "何番", reading: "なんばん", meaning: "số bao nhiêu, số mấy", category: 'kanji', lesson: 4 },
  { id: 'l4-45', kanji: "試験", reading: "しけん", meaning: "thi, kỳ thi, kiểm tra", category: 'kanji', lesson: 4 },
  { id: 'l4-46', kanji: "会議", reading: "かいぎ", meaning: "cuộc họp, hội nghị", category: 'kanji', lesson: 4 },
  { id: 'l4-47', kanji: "映画", reading: "えいが", meaning: "phim, điện ảnh", category: 'kanji', lesson: 4 },
  { id: 'l4-48', kanji: "～から", reading: "～から", meaning: "từ", category: 'general', lesson: 4 },
  { id: 'l4-49', kanji: "～まで", reading: "～まで", meaning: "đến", category: 'general', lesson: 4 },
  { id: 'l4-50', kanji: "～と～", reading: "～と～", meaning: "và (dùng để nối danh từ)", category: 'general', lesson: 4 },

  // --- BÀI 5 ---
  { id: 'l5-1', kanji: "行きます", reading: "いきます", meaning: "đi", category: 'verb', lesson: 5 },
  { id: 'l5-2', kanji: "来ます", reading: "きます", meaning: "đến", category: 'verb', lesson: 5 },
  { id: 'l5-3', kanji: "帰ります", reading: "かえります", meaning: "về", category: 'verb', lesson: 5 },
  { id: 'l5-4', kanji: "学校", reading: "がっこう", meaning: "trường học", category: 'kanji', lesson: 5 },
  { id: 'l5-5', kanji: "スーパー", reading: "すーぱー", meaning: "siêu thị", category: 'general', lesson: 5 },
  { id: 'l5-6', kanji: "駅", reading: "えき", meaning: "ga, nhà ga", category: 'kanji', lesson: 5 },
  { id: 'l5-7', kanji: "飛行機", reading: "ひこうき", meaning: "máy bay", category: 'kanji', lesson: 5 },
  { id: 'l5-8', kanji: "船", reading: "ふね", meaning: "thuyền, tàu thủy", category: 'kanji', lesson: 5 },
  { id: 'l5-9', kanji: "電車", reading: "でんしゃ", meaning: "tàu điện", category: 'kanji', lesson: 5 },
  { id: 'l5-10', kanji: "地下鉄", reading: "ちかてつ", meaning: "tàu điện ngầm", category: 'kanji', lesson: 5 },
  { id: 'l5-11', kanji: "新幹線", reading: "しんかんせん", meaning: "tàu Shinkansen (tàu điện cao tốc)", category: 'kanji', lesson: 5 },
  { id: 'l5-12', kanji: "バス", reading: "ばす", meaning: "xe buýt", category: 'general', lesson: 5 },
  { id: 'l5-13', kanji: "タクシー", reading: "たくしー", meaning: "tắc-xi", category: 'general', lesson: 5 },
  { id: 'l5-14', kanji: "自転車", reading: "じてんしゃ", meaning: "xe đạp", category: 'kanji', lesson: 5 },
  { id: 'l5-15', kanji: "歩いて", reading: "あるいて", meaning: "đi bộ", category: 'general', lesson: 5 },
  { id: 'l5-16', kanji: "人", reading: "ひと", meaning: "người", category: 'kanji', lesson: 5 },
  { id: 'l5-17', kanji: "友達", reading: "ともだち", meaning: "bạn, bạn bè", category: 'kanji', lesson: 5 },
  { id: 'l5-18', kanji: "彼", reading: "かれ", meaning: "anh ấy, bạn trai", category: 'kanji', lesson: 5 },
  { id: 'l5-19', kanji: "彼女", reading: "かのじょ", meaning: "chị ấy, bạn gái", category: 'kanji', lesson: 5 },
  { id: 'l5-20', kanji: "家族", reading: "かぞく", meaning: "gia đình", category: 'kanji', lesson: 5 },
  { id: 'l5-21', kanji: "一人で", reading: "ひとりで", meaning: "một mình", category: 'kanji', lesson: 5 },
  { id: 'l5-22', kanji: "先週", reading: "せんしゅう", meaning: "tuần trước", category: 'kanji', lesson: 5 },
  { id: 'l5-23', kanji: "今週", reading: "こんしゅう", meaning: "tuần này", category: 'kanji', lesson: 5 },
  { id: 'l5-24', kanji: "来週", reading: "らいしゅう", meaning: "tuần sau", category: 'kanji', lesson: 5 },
  { id: 'l5-25', kanji: "先月", reading: "せんげつ", meaning: "tháng trước", category: 'kanji', lesson: 5 },
  { id: 'l5-26', kanji: "今月", reading: "こんげつ", meaning: "tháng này", category: 'kanji', lesson: 5 },
  { id: 'l5-27', kanji: "来月", reading: "らいげつ", meaning: "tháng sau", category: 'kanji', lesson: 5 },
  { id: 'l5-28', kanji: "去年", reading: "きょねん", meaning: "năm ngoái", category: 'kanji', lesson: 5 },
  { id: 'l5-29', kanji: "ことし", reading: "ことし", meaning: "năm nay", category: 'general', lesson: 5 },
  { id: 'l5-30', kanji: "来年", reading: "らいねん", meaning: "sang năm", category: 'kanji', lesson: 5 },
  { id: 'l5-31', kanji: "1日", reading: "ついたち", meaning: "ngày mồng 1", category: 'kanji', lesson: 5 },
  { id: 'l5-32', kanji: "2日", reading: "ふつか", meaning: "ngày mồng 2, 2 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-33', kanji: "3日", reading: "みっか", meaning: "ngày mồng 3, 3 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-34', kanji: "4日", reading: "よっか", meaning: "ngày mồng 4, 4 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-35', kanji: "5日", reading: "いつか", meaning: "ngày mồng 5, 5 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-36', kanji: "6日", reading: "むいか", meaning: "ngày mồng 6, 6 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-37', kanji: "7日", reading: "なのか", meaning: "ngày mồng 7, 7 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-38', kanji: "8日", reading: "ようか", meaning: "ngày mồng 8, 8 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-39', kanji: "9日", reading: "ここのか", meaning: "ngày mồng 9, 9 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-40', kanji: "10日", reading: "とおか", meaning: "ngày mồng 10, 10 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-41', kanji: "14日", reading: "じゅうよっか", meaning: "ngày 14, 14 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-42', kanji: "20日", reading: "はつか", meaning: "ngày 20, 20 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-43', kanji: "24日", reading: "にじゅうよっか", meaning: "ngày 24, 24 ngày", category: 'kanji', lesson: 5 },
  { id: 'l5-44', kanji: "いつ", reading: "いつ", meaning: "bao giờ, khi nào", category: 'general', lesson: 5 },
  { id: 'l5-45', kanji: "誕生日", reading: "たんじょうび", meaning: "sinh nhật", category: 'kanji', lesson: 5 },

  // --- BÀI 6 ---
  { id: 'l6-1', kanji: "食べます", reading: "たべます", meaning: "ăn", category: 'verb', lesson: 6 },
  { id: 'l6-2', kanji: "飲みます", reading: "のみます", meaning: "uống", category: 'verb', lesson: 6 },
  { id: 'l6-3', kanji: "吸います", reading: "すいます", meaning: "hút [thuốc lá]", category: 'verb', lesson: 6 },
  { id: 'l6-4', kanji: "見ます", reading: "みます", meaning: "nhìn, xem", category: 'verb', lesson: 6 },
  { id: 'l6-5', kanji: "聞きます", reading: "ききます", meaning: "nghe", category: 'verb', lesson: 6 },
  { id: 'l6-6', kanji: "読みます", reading: "よみます", meaning: "đọc", category: 'verb', lesson: 6 },
  { id: 'l6-7', kanji: "書きます", reading: "かきます", meaning: "viết (vẽ)", category: 'verb', lesson: 6 },
  { id: 'l6-8', kanji: "買います", reading: "かいます", meaning: "mua", category: 'verb', lesson: 6 },
  { id: 'l6-9', kanji: "撮ります", reading: "とります", meaning: "chụp [ảnh]", category: 'verb', lesson: 6 },
  { id: 'l6-10', kanji: "します", reading: "します", meaning: "làm, chơi", category: 'verb', lesson: 6 },
  { id: 'l6-11', kanji: "会います", reading: "あいます", meaning: "gặp [bạn]", category: 'verb', lesson: 6 },
  { id: 'l6-12', kanji: "ごはん", reading: "ごはん", meaning: "bữa ăn, cơm", category: 'general', lesson: 6 },
  { id: 'l6-13', kanji: "朝ごはん", reading: "あさごはん", meaning: "cơm sáng, bữa sáng", category: 'kanji', lesson: 6 },
  { id: 'l6-14', kanji: "昼ごはん", reading: "ひるごはん", meaning: "cơm trưa, bữa trưa", category: 'kanji', lesson: 6 },
  { id: 'l6-15', kanji: "晩ごはん", reading: "ばんごはん", meaning: "cơm tối, bữa tối", category: 'kanji', lesson: 6 },
  { id: 'l6-16', kanji: "パン", reading: "ぱん", meaning: "bánh mì", category: 'general', lesson: 6 },
  { id: 'l6-17', kanji: "卵", reading: "たまご", meaning: "trứng", category: 'kanji', lesson: 6 },
  { id: 'l6-18', kanji: "肉", reading: "にく", meaning: "thịt", category: 'kanji', lesson: 6 },
  { id: 'l6-19', kanji: "魚", reading: "さかな", meaning: "cá", category: 'kanji', lesson: 6 },
  { id: 'l6-20', kanji: "野菜", reading: "やさい", meaning: "rau", category: 'kanji', lesson: 6 },
  { id: 'l6-21', kanji: "果物", reading: "くだもの", meaning: "hoa quả, trái cây", category: 'kanji', lesson: 6 },
  { id: 'l6-22', kanji: "水", reading: "みず", meaning: "nước", category: 'kanji', lesson: 6 },
  { id: 'l6-23', kanji: "お茶", reading: "おちゃ", meaning: "trà, trà xanh", category: 'kanji', lesson: 6 },
  { id: 'l6-24', kanji: "紅茶", reading: "こうちゃ", meaning: "trà đen", category: 'kanji', lesson: 6 },
  { id: 'l6-25', kanji: "牛乳", reading: "ぎゅうにゅう", meaning: "sữa bò", category: 'kanji', lesson: 6 },
  { id: 'l6-26', kanji: "ジュース", reading: "じゅーす", meaning: "nước hoa quả", category: 'general', lesson: 6 },
  { id: 'l6-27', kanji: "ビール", reading: "びーる", meaning: "bia", category: 'general', lesson: 6 },
  { id: 'l6-28', kanji: "[お]酒", reading: "おさけ", meaning: "rượu, rượu gạo Nhật", category: 'kanji', lesson: 6 },
  { id: 'l6-29', kanji: "たばこ", reading: "たばこ", meaning: "thuốc lá", category: 'general', lesson: 6 },
  { id: 'l6-30', kanji: "手紙", reading: "てがみ", meaning: "thư", category: 'kanji', lesson: 6 },
  { id: 'l6-31', kanji: "レポート", reading: "れぽーと", meaning: "báo cáo", category: 'general', lesson: 6 },
  { id: 'l6-32', kanji: "写真", reading: "しゃしん", meaning: "ảnh", category: 'kanji', lesson: 6 },
  { id: 'l6-33', kanji: "ビデオ", reading: "びでお", meaning: "băng video, đầu video", category: 'general', lesson: 6 },
  { id: 'l6-34', kanji: "店", reading: "みせ", meaning: "cửa hàng, tiệm", category: 'kanji', lesson: 6 },
  { id: 'l6-35', kanji: "庭", reading: "にわ", meaning: "vườn", category: 'kanji', lesson: 6 },
  { id: 'l6-36', kanji: "宿題", reading: "しゅくだい", meaning: "bài tập về nhà", category: 'kanji', lesson: 6 },
  { id: 'l6-37', kanji: "テニス", reading: "てにす", meaning: "quần vợt", category: 'general', lesson: 6 },
  { id: 'l6-38', kanji: "サッカー", reading: "さっかー", meaning: "bóng đá", category: 'general', lesson: 6 },
  { id: 'l6-39', kanji: "[お]花見", reading: "おはなみ", meaning: "(việc) ngắm hoa anh đào", category: 'kanji', lesson: 6 },
  { id: 'l6-40', kanji: "何", reading: "なに", meaning: "cái gì, gì", category: 'kanji', lesson: 6 },
  { id: 'l6-41', kanji: "いっしょに", reading: "いっしょに", meaning: "cùng, cùng nhau", category: 'general', lesson: 6 },
  { id: 'l6-42', kanji: "ちょっと", reading: "ちょっと", meaning: "một chút", category: 'general', lesson: 6 },
  { id: 'l6-43', kanji: "いつも", reading: "いつも", meaning: "luôn luôn, lúc nào cũng", category: 'general', lesson: 6 },
  { id: 'l6-44', kanji: "時々", reading: "ときどき", meaning: "thỉnh thoảng", category: 'kanji', lesson: 6 },
  { id: 'l6-45', kanji: "それから", reading: "それから", meaning: "sau đó, tiếp theo", category: 'general', lesson: 6 },

  // --- BÀI 7 ---
  { id: 'l7-1', kanji: "切ります", reading: "きります", meaning: "cắt", category: 'verb', lesson: 7 },
  { id: 'l7-2', kanji: "送ります", reading: "おくります", meaning: "gửi", category: 'verb', lesson: 7 },
  { id: 'l7-3', kanji: "あげます", reading: "あげます", meaning: "cho, tặng", category: 'verb', lesson: 7 },
  { id: 'l7-4', kanji: "もらいます", reading: "もらいます", meaning: "nhận", category: 'verb', lesson: 7 },
  { id: 'l7-5', kanji: "貸します", reading: "かします", meaning: "cho mượn, cho vay", category: 'verb', lesson: 7 },
  { id: 'l7-6', kanji: "借ります", reading: "かります", meaning: "mượn, vay", category: 'verb', lesson: 7 },
  { id: 'l7-7', kanji: "教えます", reading: "おしえます", meaning: "dạy", category: 'verb', lesson: 7 },
  { id: 'l7-8', kanji: "習います", reading: "ならいます", meaning: "học, tập", category: 'verb', lesson: 7 },
  { id: 'l7-9', kanji: "電話をかけます", reading: "でんわをかけます", meaning: "gọi [điện thoại]", category: 'verb', lesson: 7 },
  { id: 'l7-10', kanji: "手", reading: "て", meaning: "tay", category: 'kanji', lesson: 7 },
  { id: 'l7-11', kanji: "はし", reading: "はし", meaning: "đũa", category: 'general', lesson: 7 },
  { id: 'l7-12', kanji: "スプーン", reading: "すぷーん", meaning: "thìa", category: 'general', lesson: 7 },
  { id: 'l7-13', kanji: "ナイフ", reading: "ないふ", meaning: "dao", category: 'general', lesson: 7 },
  { id: 'l7-14', kanji: "フォーク", reading: "ふぉーく", meaning: "đĩa, nĩa", category: 'general', lesson: 7 },
  { id: 'l7-15', kanji: "はさみ", reading: "はさみ", meaning: "kéo", category: 'general', lesson: 7 },
  { id: 'l7-16', kanji: "パソコン", reading: "ぱそこん", meaning: "máy vi tính cá nhân", category: 'general', lesson: 7 },
  { id: 'l7-17', kanji: "ケータイ", reading: "けーたい", meaning: "điện thoại di động", category: 'general', lesson: 7 },
  { id: 'l7-18', kanji: "パンチ", reading: "ぱんち", meaning: "cái đục lỗ", category: 'general', lesson: 7 },
  { id: 'l7-19', kanji: "ホッチキス", reading: "ホッチキス", meaning: "cái dập ghim", category: 'general', lesson: 7 },
  { id: 'l7-20', kanji: "セロテープ", reading: "セロテープ", meaning: "băng dính", category: 'general', lesson: 7 },
  { id: 'l7-21', kanji: "消しゴム", reading: "けしごむ", meaning: "cái tẩy, cục tẩy", category: 'kanji', lesson: 7 },
  { id: 'l7-22', kanji: "紙", reading: "かみ", meaning: "giấy", category: 'kanji', lesson: 7 },
  { id: 'l7-23', kanji: "メール", reading: "メール", meaning: "thư điện tử, email", category: 'general', lesson: 7 },
  { id: 'l7-24', kanji: "年賀状", reading: "ねんがじょう", meaning: "thiệp mừng năm mới", category: 'kanji', lesson: 7 },
  { id: 'l7-25', kanji: "花", reading: "はな", meaning: "hoa", category: 'kanji', lesson: 7 },
  { id: 'l7-26', kanji: "シャツ", reading: "シャツ", meaning: "áo sơ mi", category: 'general', lesson: 7 },
  { id: 'l7-27', kanji: "プレゼント", reading: "プレゼント", meaning: "quà tặng, tặng phẩm", category: 'general', lesson: 7 },
  { id: 'l7-28', kanji: "荷物", reading: "にもつ", meaning: "đồ đạc, hành lý", category: 'kanji', lesson: 7 },
  { id: 'l7-29', kanji: "お金", reading: "おかね", meaning: "tiền", category: 'kanji', lesson: 7 },
  { id: 'l7-30', kanji: "切符", reading: "きっぷ", meaning: "vé", category: 'kanji', lesson: 7 },
  { id: 'l7-31', kanji: "クリスマス", reading: "クリスマス", meaning: "Giáng sinh", category: 'general', lesson: 7 },
  { id: 'l7-32', kanji: "父", reading: "ちち", meaning: "bố (của mình)", category: 'kanji', lesson: 7 },
  { id: 'l7-33', kanji: "母", reading: "はは", meaning: "mẹ (của mình)", category: 'kanji', lesson: 7 },
  { id: 'l7-34', kanji: "お父さん", reading: "おとうさん", meaning: "bố (của người khác)", category: 'kanji', lesson: 7 },
  { id: 'l7-35', kanji: "お母さん", reading: "おかあさん", meaning: "mẹ (của người khác)", category: 'kanji', lesson: 7 },
  { id: 'l7-36', kanji: "もう", reading: "もう", meaning: "đã, rồi", category: 'general', lesson: 7 },
  { id: 'l7-37', kanji: "まだ", reading: "まだ", meaning: "chưa", category: 'general', lesson: 7 },
  { id: 'l7-38', kanji: "これから", reading: "これから", meaning: "từ bây giờ, sau đây", category: 'general', lesson: 7 },
  { id: 'l7-c1', kanji: "すてきですね", reading: "すてきですね", meaning: "hay nhỉ / đẹp nhỉ", category: 'general', lesson: 7 },
  { id: 'l7-c2', kanji: "いらっしゃい", reading: "いらっしゃい", meaning: "Rất hoan nghênh anh/chị đến chơi.", category: 'general', lesson: 7 },
  { id: 'l7-c3', kanji: "どうぞ お上がりください", reading: "どうぞ おあがりください", meaning: "Mời anh/chị vào.", category: 'kanji', lesson: 7 },
  { id: 'l7-c4', kanji: "失礼します", reading: "しつれいします", meaning: "Xin phép tôi vào. (khi bước vào nhà)", category: 'kanji', lesson: 7 },
  { id: 'l7-c5', kanji: "[～は] いかがですか", reading: "[～は] いかがですか", meaning: "Anh/Chị dùng [~] nhé?", category: 'general', lesson: 7 },
  { id: 'l7-c6', kanji: "いただきます", reading: "いただきます", meaning: "Mời anh/chị dùng ~. (trước khi ăn)", category: 'general', lesson: 7 },
  { id: 'l7-c7', kanji: "ごちそうさまでした", reading: "ごちそうさまでした", meaning: "Xin cám ơn đã đãi tôi bữa ăn ngon.", category: 'general', lesson: 7 },
  { id: 'l7-q1', kanji: "スペイン", reading: "スペイン", meaning: "Tây Ban Nha", category: 'general', lesson: 7 },

  // --- BÀI 8 ---
  { id: 'l8-1', kanji: "ハンサム [な]", reading: "ハンサム", meaning: "đẹp trai", category: 'general', lesson: 8 },
  { id: 'l8-2', kanji: "きれい [な]", reading: "きれい", meaning: "đẹp, sạch", category: 'general', lesson: 8 },
  { id: 'l8-3', kanji: "静か [な]", reading: "しずか", meaning: "yên tĩnh", category: 'kanji', lesson: 8 },
  { id: 'l8-4', kanji: "にぎやか [な]", reading: "にぎやか", meaning: "náo nhiệt", category: 'general', lesson: 8 },
  { id: 'l8-5', kanji: "有名 [な]", reading: "ゆうめい", meaning: "nổi tiếng", category: 'kanji', lesson: 8 },
  { id: 'l8-6', kanji: "親切 [な]", reading: "しんせつ", meaning: "tốt bụng, thân thiện", category: 'kanji', lesson: 8 },
  { id: 'l8-7', kanji: "元気 [な]", reading: "げんき", meaning: "khỏe, khỏe khoắn", category: 'kanji', lesson: 8 },
  { id: 'l8-8', kanji: "暇 [な]", reading: "ひま", meaning: "rảnh rỗi", category: 'kanji', lesson: 8 },
  { id: 'l8-9', kanji: "便利 [な]", reading: "べんり", meaning: "tiện lợi", category: 'kanji', lesson: 8 },
  { id: 'l8-10', kanji: "すてき [な]", reading: "すてき", meaning: "đẹp, hay, tuyệt vời", category: 'general', lesson: 8 },
  { id: 'l8-11', kanji: "大きい", reading: "おおきい", meaning: "to, lớn", category: 'kanji', lesson: 8 },
  { id: 'l8-12', kanji: "小さい", reading: "ちいさい", meaning: "nhỏ, bé", category: 'kanji', lesson: 8 },
  { id: 'l8-13', kanji: "新しい", reading: "あたらしい", meaning: "mới", category: 'kanji', lesson: 8 },
  { id: 'l8-14', kanji: "古い", reading: "ふるい", meaning: "cũ", category: 'kanji', lesson: 8 },
  { id: 'l8-15', kanji: "いい（よい）", reading: "いい", meaning: "tốt", category: 'general', lesson: 8 },
  { id: 'l8-16', kanji: "悪い", reading: "わるい", meaning: "xấu", category: 'kanji', lesson: 8 },
  { id: 'l8-17', kanji: "暑い", reading: "あつい", meaning: "nóng (thời tiết)", category: 'kanji', lesson: 8 },
  { id: 'l8-18', kanji: "熱い", reading: "あつい", meaning: "nóng (cảm giác)", category: 'kanji', lesson: 8 },
  { id: 'l8-19', kanji: "寒い", reading: "samui", meaning: "lạnh (thời tiết)", category: 'kanji', lesson: 8 },
  { id: 'l8-20', kanji: "冷たい", reading: "つめたい", meaning: "lạnh (cảm giác)", category: 'kanji', lesson: 8 },
  { id: 'l8-21', kanji: "難しい", reading: "むずかしい", meaning: "khó", category: 'kanji', lesson: 8 },
  { id: 'l8-22', kanji: "易しい", reading: "やさしい", meaning: "đễ", category: 'kanji', lesson: 8 },
  { id: 'l8-23', kanji: "高い", reading: "たかい", meaning: "đắt, cao", category: 'kanji', lesson: 8 },
  { id: 'l8-24', kanji: "安い", reading: "やすい", meaning: "rẻ", category: 'kanji', lesson: 8 },
  { id: 'l8-25', kanji: "低い", reading: "ひくい", meaning: "thấp", category: 'kanji', lesson: 8 },
  { id: 'l8-26', kanji: "おもしろい", reading: "おもしろい", meaning: "thú vị, hay", category: 'general', lesson: 8 },
  { id: 'l8-27', kanji: "おいしい", reading: "おいしい", meaning: "ngon", category: 'general', lesson: 8 },
  { id: 'l8-28', kanji: "忙しい", reading: "いそがしい", meaning: "bận", category: 'kanji', lesson: 8 },
  { id: 'l8-29', kanji: "楽しい", reading: "たのしい", meaning: "vui", category: 'kanji', lesson: 8 },
  { id: 'l8-30', kanji: "白い", reading: "しろい", meaning: "trắng", category: 'kanji', lesson: 8 },
  { id: 'l8-31', kanji: "黒い", reading: "くろい", meaning: "đen", category: 'kanji', lesson: 8 },
  { id: 'l8-32', kanji: "赤い", reading: "あかい", meaning: "đỏ", category: 'kanji', lesson: 8 },
  { id: 'l8-33', kanji: "青い", reading: "あおい", meaning: "xanh da trời", category: 'kanji', lesson: 8 },
  { id: 'l8-34', kanji: "桜", reading: "さくら", meaning: "anh đào (hoa, cây)", category: 'kanji', lesson: 8 },
  { id: 'l8-35', kanji: "山", reading: "やま", meaning: "núi", category: 'kanji', lesson: 8 },
  { id: 'l8-36', kanji: "町", reading: "まち", meaning: "thị trấn, thị xã, thành phố", category: 'kanji', lesson: 8 },
  { id: 'l8-37', kanji: "食べ物", reading: "たべもの", meaning: "đồ ăn", category: 'kanji', lesson: 8 },
  { id: 'l8-38', kanji: "所", reading: "ところ", meaning: "nơi, chỗ", category: 'kanji', lesson: 8 },
  { id: 'l8-39', kanji: "寮", reading: "りょう", meaning: "kí túc xá", category: 'kanji', lesson: 8 },
  { id: 'l8-40', kanji: "レストラン", reading: "レストラン", meaning: "nhà hàng", category: 'general', lesson: 8 },
  { id: 'l8-41', kanji: "生活", reading: "せいかつ", meaning: "cuộc sống, sinh hoạt", category: 'kanji', lesson: 8 },
  { id: 'l8-42', kanji: "[お] 仕事", reading: "おしごと", meaning: "công việc", category: 'kanji', lesson: 8 },
  { id: 'l8-43', kanji: "どう", reading: "どう", meaning: "thế nào", category: 'general', lesson: 8 },
  { id: 'l8-44', kanji: "どんな ～", reading: "どんな", meaning: "~ như thế nào", category: 'general', lesson: 8 },
  { id: 'l8-45', kanji: "とても", reading: "とても", meaning: "rất, lắm", category: 'general', lesson: 8 },
  { id: 'l8-46', kanji: "あまり", reading: "あまり", meaning: "không ~ lắm (phủ định)", category: 'general', lesson: 8 },
  { id: 'l8-47', kanji: "そして", reading: "そして", meaning: "và, thêm nữa", category: 'general', lesson: 8 },
  { id: 'l8-48', kanji: "～が、～", reading: "～が", meaning: "~, nhưng ~", category: 'general', lesson: 8 },
  { id: 'l8-c1', kanji: "お元気ですか", reading: "おげんきですか", meaning: "Anh/Chị có khỏe không?", category: 'kanji', lesson: 8 },
  { id: 'l8-c2', kanji: "そうですね", reading: "そうですね", meaning: "Thế à / Để tôi xem", category: 'general', lesson: 8 },
  { id: 'l8-c3', kanji: "もう いっぱい いかがですか", reading: "もう いっぱい いかがですか", meaning: "Anh/Chị dùng thêm một chén nữa nhé?", category: 'general', lesson: 8 },
  { id: 'l8-c4', kanji: "けっこうです", reading: "けっこうです", meaning: "Không, đủ rồi ạ", category: 'general', lesson: 8 },
  { id: 'l8-c5', kanji: "もう ～ですね", reading: "もう ～ですね", meaning: "Đã ~ rồi nhỉ", category: 'general', lesson: 8 },
  { id: 'l8-c6', kanji: "そろそろ しつれいします", reading: "そろそろ しつれいします", meaning: "Sắp đến lúc tôi phải xin phép rồi", category: 'general', lesson: 8 },
  { id: 'l8-c7', kanji: "また いらっしゃってください", reading: "また いらっしゃってください", meaning: "Lần sau anh/chị lại đến chơi nhé", category: 'general', lesson: 8 },

  // --- BÀI 9 ---
  { id: 'l9-1', kanji: "わかります", reading: "わかります", meaning: "hiểu, nắm được", category: 'verb', lesson: 9 },
  { id: 'l9-2', kanji: "あります", reading: "あります", meaning: "có (sở hữu)", category: 'verb', lesson: 9 },
  { id: 'l9-3', kanji: "好き [な]", reading: "すき", meaning: "thích", category: 'general', lesson: 9 },
  { id: 'l9-4', kanji: "嫌い [な]", reading: "きらい", meaning: "ghét, không thích", category: 'general', lesson: 9 },
  { id: 'l9-5', kanji: "上手 [な]", reading: "じょうず", meaning: "giỏi, khéo", category: 'general', lesson: 9 },
  { id: 'l9-6', kanji: "下手 [な]", reading: "へた", meaning: "kém", category: 'general', lesson: 9 },
  { id: 'l9-7', kanji: "飲み物", reading: "のみもの", meaning: "đồ uống", category: 'kanji', lesson: 9 },
  { id: 'l9-8', kanji: "料理", reading: "りょうり", meaning: "món ăn, việc nấu ăn", category: 'kanji', lesson: 9 },
  { id: 'l9-9', kanji: "スポーツ", reading: "スポーツ", meaning: "thể thao", category: 'general', lesson: 9 },
  { id: 'l9-10', kanji: "野球", reading: "やきゅう", meaning: "bóng chày", category: 'kanji', lesson: 9 },
  { id: 'l9-11', kanji: "ダンス", reading: "ダンス", meaning: "nhảy, khiêu vũ", category: 'general', lesson: 9 },
  { id: 'l9-12', kanji: "旅行", reading: "りょこう", meaning: "du lịch, chuyến du lịch", category: 'kanji', lesson: 9 },
  { id: 'l9-13', kanji: "音楽", reading: "おんがく", meaning: "âm nhạc", category: 'kanji', lesson: 9 },
  { id: 'l9-14', kanji: "歌", reading: "うた", meaning: "bài hát", category: 'kanji', lesson: 9 },
  { id: 'l9-15', kanji: "クラシック", reading: "クラシック", meaning: "nhạc cổ điển", category: 'general', lesson: 9 },
  { id: 'l9-16', kanji: "ジャズ", reading: "ジャズ", meaning: "nhạc jazz", category: 'general', lesson: 9 },
  { id: 'l9-17', kanji: "コンサート", reading: "コンサート", meaning: "buổi hòa nhạc", category: 'general', lesson: 9 },
  { id: 'l9-18', kanji: "カラオケ", reading: "カラオケ", meaning: "karaoke", category: 'general', lesson: 9 },
  { id: 'l9-19', kanji: "歌舞伎", reading: "かぶき", meaning: "Kabuki (kịch truyền thống Nhật)", category: 'kanji', lesson: 9 },
  { id: 'l9-20', kanji: "絵", reading: "え", meaning: "tranh, hội họa", category: 'kanji', lesson: 9 },
  { id: 'l9-21', kanji: "字", reading: "じ", meaning: "chữ", category: 'kanji', lesson: 9 },
  { id: 'l9-22', kanji: "漢字", reading: "かんじ", meaning: "chữ Hán", category: 'kanji', lesson: 9 },
  { id: 'l9-23', kanji: "ひらがな", reading: "ひらがな", meaning: "chữ Hiragana", category: 'general', lesson: 9 },
  { id: 'l9-24', kanji: "かたかな", reading: "かたかな", meaning: "chữ Katakana", category: 'general', lesson: 9 },
  { id: 'l9-25', kanji: "ローマ字", reading: "ろーまじ", meaning: "chữ La Mã", category: 'kanji', lesson: 9 },
  { id: 'l9-26', kanji: "細かい お金", reading: "こまかいおかね", meaning: "tiền lẻ", category: 'kanji', lesson: 9 },

  // --- BÀI 10 ---
  { id: 'l10-1', kanji: "あります", reading: "あります", meaning: "có (dùng cho đồ vật, cây cối)", category: 'verb', lesson: 10 },
  { id: 'l10-2', kanji: "います", reading: "います", meaning: "có (dùng cho người và động vật)", category: 'verb', lesson: 10 },
  { id: 'l10-3', kanji: "いろいろ [な]", reading: "いろいろ", meaning: "nhiều, đa dạng", category: 'general', lesson: 10 },
  { id: 'l10-4', kanji: "男の人", reading: "おとこのひと", meaning: "người đàn ông", category: 'kanji', lesson: 10 },
  { id: 'l10-5', kanji: "女の人", reading: "おんなのひと", meaning: "người đàn bà", category: 'kanji', lesson: 10 },
  { id: 'l10-6', kanji: "男の子", reading: "おとこのこ", meaning: "cậu con trai", category: 'kanji', lesson: 10 },
  { id: 'l10-7', kanji: "女の子", reading: "おんなのこ", meaning: "cô con gái", category: 'kanji', lesson: 10 },
  { id: 'l10-8', kanji: "犬", reading: "いぬ", meaning: "chó", category: 'kanji', lesson: 10 },
  { id: 'l10-9', kanji: "猫", reading: "ねこ", meaning: "mèo", category: 'kanji', lesson: 10 },
  { id: 'l10-11', kanji: "象", reading: "ぞう", meaning: "voi", category: 'kanji', lesson: 10 },
  { id: 'l10-12', kanji: "木", reading: "き", meaning: "cây, gỗ", category: 'kanji', lesson: 10 },
  { id: 'l10-13', kanji: "物", reading: "もの", meaning: "vật, đồ vật", category: 'kanji', lesson: 10 },
  { id: 'l10-14', kanji: "電池", reading: "でんち", meaning: "pin", category: 'kanji', lesson: 10 },
  { id: 'l10-15', kanji: "箱", reading: "はこ", meaning: "hộp", category: 'kanji', lesson: 10 },
  { id: 'l10-16', kanji: "スイッチ", reading: "スイッチ", meaning: "công tắc", category: 'general', lesson: 10 },
  { id: 'l10-17', kanji: "冷蔵庫", reading: "れいぞうこ", meaning: "tủ lạnh", category: 'kanji', lesson: 10 },
  { id: 'l10-18', kanji: "テーブル", reading: "テーブル", meaning: "bàn", category: 'general', lesson: 10 },
  { id: 'l10-19', kanji: "ベッド", reading: "ベッド", meaning: "giường", category: 'general', lesson: 10 },
  { id: 'l10-20', kanji: "棚", reading: "たな", meaning: "giá sách, kệ sách", category: 'kanji', lesson: 10 },
  { id: 'l10-21', kanji: "ドア", reading: "ドア", meaning: "cửa", category: 'general', lesson: 10 },
  { id: 'l10-22', kanji: "窓", reading: "まど", meaning: "cửa sổ", category: 'kanji', lesson: 10 },
  { id: 'l10-23', kanji: "ポスト", reading: "ポスト", meaning: "hộp thư, hòm thư", category: 'general', lesson: 10 },
  { id: 'l10-24', kanji: "ビル", reading: "ビル", meaning: "tòa nhà", category: 'general', lesson: 10 },
  { id: 'l10-25', kanji: "ATM", reading: "ATM", meaning: "máy rút tiền tự động, ATM", category: 'general', lesson: 10 },
  { id: 'l10-26', kanji: "コンビニ", reading: "コンビニ", meaning: "cửa hàng tiện lợi", category: 'general', lesson: 10 },
  { id: 'l10-27', kanji: "公園", reading: "こうえん", meaning: "công viên", category: 'kanji', lesson: 10 },
  { id: 'l10-28', kanji: "喫茶店", reading: "きっさてん", meaning: "quán giải khát, quán cà-phê", category: 'kanji', lesson: 10 },
  { id: 'l10-29', kanji: "～屋", reading: "～や", meaning: "hiệu ~, cửa hàng ~", category: 'kanji', lesson: 10 },
  { id: 'l10-30', kanji: "乗り場", reading: "のりば", meaning: "điểm đón tắc-xi, tàu, v.v.", category: 'kanji', lesson: 10 },
  { id: 'l10-31', kanji: "県", reading: "けん", meaning: "tỉnh", category: 'kanji', lesson: 10 },
  { id: 'l10-32', kanji: "上", reading: "うえ", meaning: "trên", category: 'kanji', lesson: 10 },
  { id: 'l10-33', kanji: "下", reading: "した", meaning: "dưới", category: 'kanji', lesson: 10 },
  { id: 'l10-34', kanji: "前", reading: "まえ", meaning: "trước", category: 'kanji', lesson: 10 },
  { id: 'l10-35', kanji: "うしろ", reading: "うしろ", meaning: "sau", category: 'general', lesson: 10 },
  { id: 'l10-36', kanji: "右", reading: "みぎ", meaning: "(bên) phải", category: 'kanji', lesson: 10 },
  { id: 'l10-37', kanji: "左", reading: "ひだり", meaning: "(bên) trái", category: 'kanji', lesson: 10 },
  { id: 'l10-38', kanji: "中", reading: "なか", meaning: "trong, giữa", category: 'kanji', lesson: 10 },
  { id: 'l10-39', kanji: "外", reading: "そと", meaning: "ngoài", category: 'kanji', lesson: 10 },
  { id: 'l10-40', kanji: "隣", reading: "となり", meaning: "bên cạnh", category: 'kanji', lesson: 10 },
  { id: 'l10-41', kanji: "近く", reading: "ちかく", meaning: "gần", category: 'kanji', lesson: 10 },
  { id: 'l10-42', kanji: "間", reading: "あいだ", meaning: "giữa, ở giữa", category: 'kanji', lesson: 10 },

  // --- BÀI 11 ---
  { id: 'l11-1', kanji: "います [子供が～]", reading: "います", meaning: "có [con]", category: 'verb', lesson: 11 },
  { id: 'l11-2', kanji: "います [日本に～]", reading: "います", meaning: "ở [Nhật]", category: 'verb', lesson: 11 },
  { id: 'l11-3', kanji: "かかります", reading: "かかります", meaning: "mất, tốn (thời gian, tiền bạc)", category: 'verb', lesson: 11 },
  { id: 'l11-4', kanji: "休みます [会社を～]", reading: "やすみます", meaning: "nghỉ [làm việc]", category: 'kanji', lesson: 11 },
  { id: 'l11-5', kanji: "1つ", reading: "ひとつ", meaning: "một cái", category: 'kanji', lesson: 11 },
  { id: 'l11-6', kanji: "2つ", reading: "ふたつ", meaning: "hai cái", category: 'kanji', lesson: 11 },
  { id: 'l11-7', kanji: "3つ", reading: "みっつ", meaning: "ba cái", category: 'kanji', lesson: 11 },
  { id: 'l11-8', kanji: "4つ", reading: "よっつ", meaning: "bốn cái", category: 'kanji', lesson: 11 },
  { id: 'l11-9', kanji: "5つ", reading: "いつつ", meaning: "năm cái", category: 'kanji', lesson: 11 },
  { id: 'l11-10', kanji: "6つ", reading: "むっつ", meaning: "sáu cái", category: 'kanji', lesson: 11 },
  { id: 'l11-11', kanji: "7つ", reading: "ななつ", meaning: "bảy cái", category: 'kanji', lesson: 11 },
  { id: 'l11-12', kanji: "8つ", reading: "やっつ", meaning: "tám cái", category: 'kanji', lesson: 11 },
  { id: 'l11-13', kanji: "9つ", reading: "ここのつ", meaning: "chín cái", category: 'kanji', lesson: 11 },
  { id: 'l11-14', kanji: "10", reading: "とお", meaning: "mười cái", category: 'kanji', lesson: 11 },
  { id: 'l11-15', kanji: "いくつ", reading: "いくつ", meaning: "mấy cái, bao nhiêu cái", category: 'general', lesson: 11 },
  { id: 'l11-16', kanji: "1人", reading: "ひとり", meaning: "một người", category: 'kanji', lesson: 11 },
  { id: 'l11-17', kanji: "2人", reading: "ふたり", meaning: "hai người", category: 'kanji', lesson: 11 },
  { id: 'l11-18', kanji: "～人", reading: "～にん", meaning: "～ người", category: 'kanji', lesson: 11 },
  { id: 'l11-19', kanji: "～台", reading: "～だい", meaning: "～ cái, chiếc (máy móc, xe cộ)", category: 'kanji', lesson: 11 },
  { id: 'l11-20', kanji: "～枚", reading: "～まい", meaning: "～ tờ, tấm (vật mỏng)", category: 'kanji', lesson: 11 },
  { id: 'l11-21', kanji: "～回", reading: "～かい", meaning: "～ lần", category: 'kanji', lesson: 11 },
  { id: 'l11-22', kanji: "りんご", reading: "りんご", meaning: "táo", category: 'general', lesson: 11 },
  { id: 'l11-23', kanji: "みかん", reading: "みかん", meaning: "quýt", category: 'general', lesson: 11 },
  { id: 'l11-24', kanji: "サンドイッチ", reading: "サンドイッチ", meaning: "bánh san-uých", category: 'general', lesson: 11 },
  { id: 'l11-25', kanji: "カレー [ライス]", reading: "カレー", meaning: "món [cơm] cà-ri", category: 'general', lesson: 11 },
  { id: 'l11-26', kanji: "アイスクリーム", reading: "アイスクリーム", meaning: "kem", category: 'general', lesson: 11 },
  { id: 'l11-27', kanji: "切手", reading: "きって", meaning: "tem", category: 'kanji', lesson: 11 },
  { id: 'l11-28', kanji: "はがき", reading: "はがき", meaning: "bưu thiếp", category: 'general', lesson: 11 },
  { id: 'l11-29', kanji: "封筒", reading: "ふうとう", meaning: "phong bì", category: 'kanji', lesson: 11 },
  { id: 'l11-30', kanji: "両親", reading: "りょうしん", meaning: "bố mẹ", category: 'kanji', lesson: 11 },
  { id: 'l11-31', kanji: "兄弟", reading: "きょうだい", meaning: "anh chị em", category: 'kanji', lesson: 11 },
  { id: 'l11-32', kanji: "兄", reading: "あに", meaning: "anh trai (mình)", category: 'kanji', lesson: 11 },
  { id: 'l11-33', kanji: "お兄さん", reading: "おにいさん", meaning: "anh trai (người khác)", category: 'kanji', lesson: 11 },
  { id: 'l11-34', kanji: "姉", reading: "あね", meaning: "chị gái (mình)", category: 'kanji', lesson: 11 },
  { id: 'l11-35', kanji: "お姉さん", reading: "おねえさん", meaning: "chị gái (người khác)", category: 'kanji', lesson: 11 },
  { id: 'l11-36', kanji: "弟", reading: "おとうと", meaning: "em trai (mình)", category: 'kanji', lesson: 11 },
  { id: 'l11-37', kanji: "弟さん", reading: "おとうとさん", meaning: "em trai (người khác)", category: 'kanji', lesson: 11 },
  { id: 'l11-38', kanji: "妹", reading: "いもうと", meaning: "em gái (mình)", category: 'kanji', lesson: 11 },
  { id: 'l11-39', kanji: "妹さん", reading: "いもうとさん", meaning: "em gái (người khác)", category: 'kanji', lesson: 11 },
  { id: 'l11-40', kanji: "外国", reading: "がいこく", meaning: "nước ngoài", category: 'kanji', lesson: 11 },
  { id: 'l11-41', kanji: "留学生", reading: "りゅうがくせい", meaning: "lưu học sinh", category: 'kanji', lesson: 11 },
  { id: 'l11-42', kanji: "クラス", reading: "クラス", meaning: "lớp học", category: 'general', lesson: 11 },
  { id: 'l11-43', kanji: "～時間", reading: "～じかん", meaning: "～ tiếng", category: 'kanji', lesson: 11 },
  { id: 'l11-44', kanji: "～週間", reading: "～しゅうかん", meaning: "～ tuần", category: 'kanji', lesson: 11 },
  { id: 'l11-45', kanji: "～か月", reading: "～かげつ", meaning: "～ tháng", category: 'kanji', lesson: 11 },
  { id: 'l11-46', kanji: "～年", reading: "～ねん", meaning: "～ năm", category: 'kanji', lesson: 11 },
  { id: 'l11-47', kanji: "～くらい", reading: "～くらい", meaning: "khoảng ～", category: 'general', lesson: 11 },
  { id: 'l11-48', kanji: "どのくらい", reading: "どのくらい", meaning: "bao lâu", category: 'general', lesson: 11 },
  { id: 'l11-49', kanji: "全部で", reading: "ぜんぶで", meaning: "tổng cộng", category: 'kanji', lesson: 11 },
  { id: 'l11-50', kanji: "みんな", reading: "みんな", meaning: "tất cả", category: 'general', lesson: 11 },
  { id: 'l11-51', kanji: "～だけ", reading: "～だけ", meaning: "chỉ ～", category: 'general', lesson: 11 },

  // --- BÀI 12 ---
  { id: 'l12-1', kanji: "季節", reading: "きせつ", meaning: "mùa", category: 'kanji', lesson: 12 },
  { id: 'l12-2', kanji: "春", reading: "はる", meaning: "mùa xuân", category: 'kanji', lesson: 12 },
  { id: 'l12-3', kanji: "夏", reading: "なつ", meaning: "mùa hè", category: 'kanji', lesson: 12 },
  { id: 'l12-4', kanji: "秋", reading: "あき", meaning: "mùa thu", category: 'kanji', lesson: 12 },
  { id: 'l12-5', kanji: "冬", reading: "ふゆ", meaning: "mùa đông", category: 'kanji', lesson: 12 },
  { id: 'l12-6', kanji: "天気", reading: "てんき", meaning: "thời tiết", category: 'kanji', lesson: 12 },
  { id: 'l12-7', kanji: "雨", reading: "あめ", meaning: "mưa", category: 'kanji', lesson: 12 },
  { id: 'l12-8', kanji: "雪", reading: "ゆき", meaning: "tuyết", category: 'kanji', lesson: 12 },
  { id: 'l12-9', kanji: "曇り", reading: "くもり", meaning: "có mây", category: 'kanji', lesson: 12 },
  { id: 'l12-10', kanji: "ホテル", reading: "ホテル", meaning: "khách sạn", category: 'general', lesson: 12 },
  { id: 'l12-11', kanji: "空港", reading: "くうこう", meaning: "sân bay", category: 'kanji', lesson: 12 },
  { id: 'l12-12', kanji: "海", reading: "うみ", meaning: "biển, đại dương", category: 'kanji', lesson: 12 },
  { id: 'l12-13', kanji: "世界", reading: "せかい", meaning: "thế giới", category: 'kanji', lesson: 12 },
  { id: 'l12-14', kanji: "パーティー", reading: "パーティー", meaning: "tiệc", category: 'general', lesson: 12 },
  { id: 'l12-15', kanji: "[お] 祭り", reading: "おまつり", meaning: "lễ hội", category: 'kanji', lesson: 12 },
  { id: 'l12-16', kanji: "すき焼き", reading: "すきやき", meaning: "Sukiyaki (món lẩu thịt bò)", category: 'kanji', lesson: 12 },
  { id: 'l12-17', kanji: "刺身", reading: "さしみ", meaning: "Sashimi (món gỏi cá sống)", category: 'kanji', lesson: 12 },
  { id: 'l12-18', kanji: "[お] すし", reading: "おすし", meaning: "Sushi (cơm trộn giấm có cá tươi)", category: 'general', lesson: 12 },
  { id: 'l12-19', kanji: "てんぷら", reading: "てんぷら", meaning: "Tempura (hải sản/rau chiên tẩm bột)", category: 'general', lesson: 12 },
  { id: 'l12-20', kanji: "豚肉", reading: "ぶたにく", meaning: "thịt heo, thịt lợn", category: 'kanji', lesson: 12 },
  { id: 'l12-21', kanji: "とり肉", reading: "とりにく", meaning: "thịt gà", category: 'kanji', lesson: 12 },
  { id: 'l12-22', kanji: "牛肉", reading: "ぎゅうにく", meaning: "thịt bò", category: 'kanji', lesson: 12 },
  { id: 'l12-23', kanji: "レモン", reading: "レモン", meaning: "chanh", category: 'general', lesson: 12 },
  { id: 'l12-24', kanji: "生け花", reading: "いけばな", meaning: "nghệ thuật cắm hoa", category: 'kanji', lesson: 12 },
  { id: 'l12-25', kanji: "紅葉", reading: "モミジ", meaning: "cây lá đỏ, lá đỏ", category: 'kanji', lesson: 12 },
  { id: 'l12-26', kanji: "どちら", reading: "どちら", meaning: "cái nào (trong hai cái)", category: 'general', lesson: 12 },
  { id: 'l12-27', kanji: "どちらも", reading: "どちらも", meaning: "cả hai", category: 'general', lesson: 12 },
  { id: 'l12-28', kanji: "いちばん", reading: "いちばん", meaning: "nhất", category: 'general', lesson: 12 },
  { id: 'l12-29', kanji: "ずっと", reading: "ずっと", meaning: "(hơn) hẳn, suốt", category: 'general', lesson: 12 },
  { id: 'l12-30', kanji: "初めて", reading: "はじめて", meaning: "lần đầu tiên", category: 'kanji', lesson: 12 },
  { id: 'l12-c1', kanji: "ただいま", reading: "ただいま", meaning: "Tôi đã về đây. (nói khi về nhà)", category: 'general', lesson: 12 },
  { id: 'l12-c2', kanji: "お帰りなさい", reading: "おかえりなさい", meaning: "Anh/Chị đã về đấy à.", category: 'kanji', lesson: 12 },
  { id: 'l12-c3', kanji: "わあ、すごい人ですね", reading: "わあ、すごいひとですね", meaning: "Ôi, người đông quá nhỉ!", category: 'kanji', lesson: 12 },
  { id: 'l12-c4', kanji: "疲れました", reading: "つかれました", meaning: "Tôi mệt rồi.", category: 'verb', lesson: 12 },

  // --- BÀI 13 ---
  { id: 'l13-1', kanji: "遊びます", reading: "あそびます", meaning: "chơi", category: 'verb', lesson: 13 },
  { id: 'l13-2', kanji: "泳ぎます", reading: "およぎます", meaning: "bơi", category: 'verb', lesson: 13 },
  { id: 'l13-3', kanji: "迎えます", reading: "むかえます", meaning: "đón", category: 'verb', lesson: 13 },
  { id: 'l13-4', kanji: "疲れます", reading: "つかれます", meaning: "mệt", category: 'verb', lesson: 13 },
  { id: 'l13-5', kanji: "結婚します", reading: "けっこんします", meaning: "kết hôn, lập gia đình", category: 'verb', lesson: 13 },
  { id: 'l13-6', kanji: "買い物します", reading: "かいものします", meaning: "mua sắm, mua hàng", category: 'verb', lesson: 13 },
  { id: 'l13-7', kanji: "食事します", reading: "しょくじします", meaning: "ăn cơm, dùng bữa", category: 'verb', lesson: 13 },
  { id: 'l13-8', kanji: "散歩します [公園を～]", reading: "さんぽします", meaning: "đi dạo [ở công viên]", category: 'verb', lesson: 13 },
  { id: 'l13-9', kanji: "大変 [な]", reading: "たいへん", meaning: "vất vả, khó khăn, khổ", category: 'general', lesson: 13 },
  { id: 'l13-10', kanji: "欲しい", reading: "ほしい", meaning: "muốn có", category: 'kanji', lesson: 13 },
  { id: 'l13-11', kanji: "広い", reading: "ひろい", meaning: "rộng", category: 'kanji', lesson: 13 },
  { id: 'l13-12', kanji: "狭い", reading: "せまい", meaning: "chật, hẹp", category: 'kanji', lesson: 13 },
  { id: 'l13-13', kanji: "のどが かわきます", reading: "のどがかわきます", meaning: "khát", category: 'general', lesson: 13 },
  { id: 'l13-14', kanji: "おなかが すきます", reading: "おなかがすきます", meaning: "đói", category: 'general', lesson: 13 },
  { id: 'l13-15', kanji: "そうしましょう", reading: "そうしましょう", meaning: "Nhất trí. Hãy làm vậy đi.", category: 'general', lesson: 13 },
  { id: 'l13-16', kanji: "ご注文は？", reading: "ごちゅうもんは？", meaning: "Anh/Chị dùng món gì ạ?", category: 'kanji', lesson: 13 },
  { id: 'l13-17', kanji: "定食", reading: "ていしょく", meaning: "cơm suất, cơm phần", category: 'kanji', lesson: 13 },
  { id: 'l13-18', kanji: "牛丼", reading: "ぎゅうどん", meaning: "món cơm với thịt bò ở trên", category: 'kanji', lesson: 13 },
  { id: 'l13-19', kanji: "[少々] お待ちください", reading: "おまちください", meaning: "Xin vui lòng đợi [một chút].", category: 'kanji', lesson: 13 },
  { id: 'l13-20', kanji: "～で ございます", reading: "でございます", meaning: "(cách nói lịch sự của です)", category: 'general', lesson: 13 },
  { id: 'l13-21', kanji: "別々に", reading: "べつべつに", meaning: "riêng, riêng ra", category: 'kanji', lesson: 13 },

  // --- BÀI 14 ---
  { id: 'l14-1', kanji: "つけます", reading: "つけます", meaning: "bật (điện, máy điều hòa)", category: 'verb', lesson: 14 },
  { id: 'l14-2', kanji: "消します", reading: "けします", meaning: "tắt", category: 'verb', lesson: 14 },
  { id: 'l14-3', kanji: "開けます", reading: "あけます", meaning: "mở (cửa, cửa sổ)", category: 'verb', lesson: 14 },
  { id: 'l14-4', kanji: "閉めます", reading: "しめます", meaning: "đóng", category: 'verb', lesson: 14 },
  { id: 'l14-5', kanji: "急ぎます", reading: "いそぎます", meaning: "vội, gấp", category: 'verb', lesson: 14 },
  { id: 'l14-6', kanji: "待ちます", reading: "まちます", meaning: "đợi, chờ", category: 'verb', lesson: 14 },
  { id: 'l14-7', kanji: "持ちます", reading: "もちます", meaning: "mang, cầm", category: 'verb', lesson: 14 },
  { id: 'l14-8', kanji: "取ります", reading: "とります", meaning: "lấy, chuyển", category: 'verb', lesson: 14 },
  { id: 'l14-9', kanji: "手伝います", reading: "てつだいます", meaning: "giúp (làm việc gì)", category: 'verb', lesson: 14 },
  { id: 'l14-10', kanji: "呼びます", reading: "よびます", meaning: "gọi", category: 'verb', lesson: 14 },
  { id: 'l14-11', kanji: "話します", reading: "はなします", meaning: "nói, nói chuyện", category: 'verb', lesson: 14 },
  { id: 'l14-12', kanji: "使います", reading: "つかいます", meaning: "dùng, sử dụng", category: 'verb', lesson: 14 },
  { id: 'l14-13', kanji: "止めます", reading: "とめます", meaning: "dừng, đỗ", category: 'verb', lesson: 14 },
  { id: 'l14-14', kanji: "見せます", reading: "みせます", meaning: "cho xem, trình", category: 'verb', lesson: 14 },
  { id: 'l14-15', kanji: "教えます [住所を～]", reading: "おしえます", meaning: "nói, cho biết [địa chỉ]", category: 'verb', lesson: 14 },
  { id: 'l14-16', kanji: "座ります", reading: "すわります", meaning: "ngồi", category: 'verb', lesson: 14 },
  { id: 'l14-17', kanji: "立ちます", reading: "たちます", meaning: "đứng", category: 'verb', lesson: 14 },
  { id: 'l14-18', kanji: "入ります [喫茶店に～]", reading: "はいります", meaning: "vào [quán giải khát]", category: 'verb', lesson: 14 },
  { id: 'l14-19', kanji: "出ます [喫茶店を～]", reading: "でます", meaning: "ra, ra khỏi [quán giải khát]", category: 'verb', lesson: 14 },
  { id: 'l14-20', kanji: "降ります [雨が～]", reading: "ふります", meaning: "mưa", category: 'verb', lesson: 14 },
  { id: 'l14-21', kanji: "コピーします", reading: "コピーします", meaning: "copy, phô-tô", category: 'verb', lesson: 14 },
  { id: 'l14-22', kanji: "電気", reading: "でんき", meaning: "điện, đèn điện", category: 'kanji', lesson: 14 },
  { id: 'l14-23', kanji: "エアコン", reading: "エアコン", meaning: "máy điều hòa", category: 'general', lesson: 14 },
  { id: 'l14-24', kanji: "パスポート", reading: "パスポート", meaning: "hộ chiếu", category: 'general', lesson: 14 },
  { id: 'l14-25', kanji: "名前", reading: "なまえ", meaning: "tên", category: 'kanji', lesson: 14 },
  { id: 'l14-26', kanji: "住所", reading: "じゅうしょ", meaning: "địa chỉ", category: 'kanji', lesson: 14 },
  { id: 'l14-27', kanji: "地図", reading: "ちず", meaning: "bản đồ", category: 'kanji', lesson: 14 },
  { id: 'l14-28', kanji: "塩", reading: "しお", meaning: "muối", category: 'kanji', lesson: 14 },
  { id: 'l14-29', kanji: "砂糖", reading: "さとう", meaning: "đường", category: 'kanji', lesson: 14 },
  { id: 'l14-30', kanji: "問題", reading: "もんだい", meaning: "câu hỏi, vấn đề", category: 'kanji', lesson: 14 },
  { id: 'l14-31', kanji: "答え", reading: "こたえ", meaning: "câu trả lời", category: 'kanji', lesson: 14 },
  { id: 'l14-32', kanji: "読み方", reading: "よみかた", meaning: "cách đọc", category: 'kanji', lesson: 14 },
  { id: 'l14-33', kanji: "～方", reading: "～かた", meaning: "cách ～", category: 'general', lesson: 14 },
  { id: 'l14-34', kanji: "まっすぐ", reading: "まっすぐ", meaning: "thẳng", category: 'general', lesson: 14 },
  { id: 'l14-35', kanji: "ゆっくり", reading: "ゆっくり", meaning: "chậm, thong thả, thoải mái", category: 'general', lesson: 14 },
  { id: 'l14-36', kanji: "すぐ", reading: "すぐ", meaning: "ngay, lập tức", category: 'general', lesson: 14 },
  { id: 'l14-37', kanji: "また", reading: "また", meaning: "lại", category: 'general', lesson: 14 },
  { id: 'l14-38', kanji: "あとで", reading: "あとで", meaning: "sau", category: 'general', lesson: 14 },
  { id: 'l14-39', kanji: "もう 少し", reading: "もうすこし", meaning: "thêm một chút nữa", category: 'kanji', lesson: 14 },
  { id: 'l14-40', kanji: "もう ～", reading: "もう", meaning: "thêm ～", category: 'general', lesson: 14 },

  // --- BÀI 15 ---
  { id: 'l15-1', kanji: "置きます", reading: "おきます", meaning: "đặt, để", category: 'verb', lesson: 15 },
  { id: 'l15-2', kanji: "作ります", reading: "つくります", meaning: "chế biến, sản xuất, làm", category: 'verb', lesson: 15 },
  { id: 'l15-3', kanji: "売ります", reading: "うります", meaning: "bán", category: 'verb', lesson: 15 },
  { id: 'l15-4', kanji: "知ります", reading: "しります", meaning: "biết", category: 'verb', lesson: 15 },
  { id: 'l15-5', kanji: "住みます", reading: "すみまs", meaning: "sống, ở", category: 'verb', lesson: 15 },
  { id: 'l15-6', kanji: "研究します", reading: "けんきゅうします", meaning: "nghiên cứu", category: 'verb', lesson: 15 },
  { id: 'l15-7', kanji: "資料", reading: "しりょう", meaning: "tài liệu", category: 'kanji', lesson: 15 },
  { id: 'l15-8', kanji: "カタログ", reading: "カタログ", meaning: "catalogue", category: 'general', lesson: 15 },
  { id: 'l15-9', kanji: "時刻表", reading: "じこくひょう", meaning: "bảng giờ chạy tàu", category: 'kanji', lesson: 15 },
  { id: 'l15-10', kanji: "服", reading: "ふく", meaning: "quần áo", category: 'kanji', lesson: 15 },
  { id: 'l15-11', kanji: "製品", reading: "せいひん", meaning: "sản phẩm", category: 'kanji', lesson: 15 },
  { id: 'l15-12', kanji: "ソフト", reading: "ソフト", meaning: "phần mềm", category: 'general', lesson: 15 },
  { id: 'l15-13', kanji: "専門", reading: "せんもん", meaning: "chuyên môn", category: 'kanji', lesson: 15 },
  { id: 'l15-14', kanji: "歯医者", reading: "はいしゃ", meaning: "nha sĩ", category: 'kanji', lesson: 15 },
  { id: 'l15-15', kanji: "床屋", reading: "とこや", meaning: "hiệu cắt tóc", category: 'kanji', lesson: 15 },
  { id: 'l15-16', kanji: "独身", reading: "どくしん", meaning: "độc thân", category: 'kanji', lesson: 15 },

  // --- BÀI 16 ---
  { id: 'l16-1', kanji: "乗ります [電車に～]", reading: "のります", meaning: "đi, lên [tàu]", category: 'verb', lesson: 16 },
  { id: 'l16-2', kanji: "降ります [電車を～]", reading: "おります", meaning: "xuống [tàu]", category: 'verb', lesson: 16 },
  { id: 'l16-3', kanji: "乗り換えます", reading: "のりかえます", meaning: "chuyển, đổi (tàu)", category: 'verb', lesson: 16 },
  { id: 'l16-4', kanji: "浴びます [シャワーを～]", reading: "あびます", meaning: "tắm [vòi hoa sen]", category: 'verb', lesson: 16 },
  { id: 'l16-5', kanji: "入れます", reading: "いれます", meaning: "cho vào, bỏ vào", category: 'verb', lesson: 16 },
  { id: 'l16-6', kanji: "出します", reading: "だします", meaning: "lấy ra, đưa ra, gửi", category: 'verb', lesson: 16 },
  { id: 'l16-7', kanji: "下ろします [お金を～]", reading: "おろします", meaning: "rút [tiền]", category: 'verb', lesson: 16 },
  { id: 'l16-8', kanji: "入ります [大学に～]", reading: "はいります", meaning: "vào [đại học]", category: 'verb', lesson: 16 },
  { id: 'l16-9', kanji: "出ます [大学を～]", reading: "でます", meaning: "ra, tốt nghiệp [đại học]", category: 'verb', lesson: 16 },
  { id: 'l16-10', kanji: "押します", reading: "おします", meaning: "bấm, ấn", category: 'verb', lesson: 16 },
  { id: 'l16-11', kanji: "飲みます", reading: "のみます", meaning: "uống (bia, rượu)", category: 'verb', lesson: 16 },
  { id: 'l16-12', kanji: "始めます", reading: "はじめます", meaning: "bắt đầu", category: 'verb', lesson: 16 },
  { id: 'l16-13', kanji: "見学します", reading: "けんがくします", meaning: "tham quan kiến tập", category: 'verb', lesson: 16 },
  { id: 'l16-14', kanji: "電話します", reading: "でんわします", meaning: "gọi điện thoại", category: 'verb', lesson: 16 },
  { id: 'l16-15', kanji: "若い", reading: "わかい", meaning: "trẻ", category: 'general', lesson: 16 },
  { id: 'l16-16', kanji: "長い", reading: "ながい", meaning: "dài", category: 'kanji', lesson: 16 },
  { id: 'l16-17', kanji: "短い", reading: "みじかい", meaning: "ngắn", category: 'kanji', lesson: 16 },
  { id: 'l16-18', kanji: "明るい", reading: "あかるい", meaning: "sáng", category: 'kanji', lesson: 16 },
  { id: 'l16-19', kanji: "暗い", reading: "くらい", meaning: "tối", category: 'kanji', lesson: 16 },
  { id: 'l16-20', kanji: "体", reading: "からだ", meaning: "người, cơ thể", category: 'kanji', lesson: 16 },
  { id: 'l16-21', kanji: "頭", reading: "あたま", meaning: "đầu", category: 'kanji', lesson: 16 },
  { id: 'l16-22', kanji: "髪", reading: "かみ", meaning: "tóc", category: 'kanji', lesson: 16 },
  { id: 'l16-23', kanji: "顔", reading: "かお", meaning: "mặt", category: 'kanji', lesson: 16 },
  { id: 'l16-24', kanji: "目", reading: "め", meaning: "mắt", category: 'kanji', lesson: 16 },
  { id: 'l16-25', kanji: "耳", reading: "みみ", meaning: "tai", category: 'kanji', lesson: 16 },
  { id: 'l16-26', kanji: "鼻", reading: "はな", meaning: "mũi", category: 'kanji', lesson: 16 },
  { id: 'l16-27', kanji: "口", reading: "くち", meaning: "miệng", category: 'kanji', lesson: 16 },
  { id: 'l16-28', kanji: "歯", reading: "は", meaning: "răng", category: 'kanji', lesson: 16 },
  { id: 'l16-29', kanji: "おなか", reading: "おなか", meaning: "bụng", category: 'general', lesson: 16 },
  { id: 'l16-30', kanji: "足", reading: "あし", meaning: "chân", category: 'kanji', lesson: 16 },
  { id: 'l16-31', kanji: "背", reading: "せ", meaning: "chiều cao (cơ thể)", category: 'kanji', lesson: 16 },
  { id: 'l16-32', kanji: "サービス", reading: "サービス", meaning: "dịch vụ", category: 'general', lesson: 16 },
  { id: 'l16-33', kanji: "ジョギング", reading: "ジョギング", meaning: "việc chạy bộ", category: 'general', lesson: 16 },
  { id: 'l16-34', kanji: "シャワー", reading: "シャワー", meaning: "vòi hoa sen", category: 'general', lesson: 16 },
  { id: 'l16-35', kanji: "緑", reading: "みどり", meaning: "màu xanh lá cây, cây xanh", category: 'kanji', lesson: 16 },
  { id: 'l16-36', kanji: "[お] 寺", reading: "おてら", meaning: "chùa", category: 'kanji', lesson: 16 },
  { id: 'l16-37', kanji: "神社", reading: "じんじゃ", meaning: "đền thờ đạo Thần", category: 'kanji', lesson: 16 },
  { id: 'l16-38', kanji: "一番", reading: "いちばん", meaning: "số 1, nhất", category: 'kanji', lesson: 16 },
  { id: 'l16-39', kanji: "どうやって", reading: "どうやって", meaning: "làm thế nào", category: 'general', lesson: 16 },
  { id: 'l16-40', kanji: "どの～", reading: "どの", meaning: "~ nào", category: 'general', lesson: 16 },
  { id: 'l16-41', kanji: "どれ", reading: "どれ", meaning: "cái nào", category: 'general', lesson: 16 },
  { id: 'l16-42', kanji: "すごいですね", reading: "すごいですね", meaning: "Thật là tuyệt vời!/Kinh quá nhỉ!", category: 'general', lesson: 16 },
  { id: 'l16-43', kanji: "まだまだです", reading: "まだまだです", meaning: "tôi còn phải cố gắng nhiều lắm.", category: 'general', lesson: 16 },
  { id: 'l16-44', kanji: "お引き出しですか", reading: "おひきだしですか", meaning: "Anh/Chị rút tiền ạ?", category: 'kanji', lesson: 16 },
  { id: 'l16-45', kanji: "まず", reading: "まず", meaning: "trước hết, đầu tiên", category: 'general', lesson: 16 },
  { id: 'l16-46', kanji: "次に", reading: "つぎに", meaning: "tiếp theo, sau đó", category: 'kanji', lesson: 16 },
  { id: 'l16-47', kanji: "キャッシュカード", reading: "キャッシュカード", meaning: "thẻ rút tiền mặt, thẻ ATM", category: 'general', lesson: 16 },
  { id: 'l16-48', kanji: "暗証番号", reading: "あんしょうばんごう", meaning: "mã số bí mật (mật khẩu)", category: 'kanji', lesson: 16 },
  { id: 'l16-49', kanji: "金額", reading: "きんがく", meaning: "số tiền, khoản tiền", category: 'kanji', lesson: 16 },
  { id: 'l10-50', kanji: "確認", reading: "かくにん", meaning: "sự xác nhận, sự kiểm tra lại", category: 'kanji', lesson: 16 },
  { id: 'l16-51', kanji: "ボタン", reading: "ボタン", meaning: "nút", category: 'general', lesson: 16 },
  { id: 'l16-52', kanji: "JR", reading: "JR", meaning: "Công ty Đường sắt Nhật Bản", category: 'general', lesson: 16 },
  { id: 'l16-53', kanji: "ゆきまつり", reading: "ゆきまつり", meaning: "Lễ hội tuyết", category: 'kanji', lesson: 16 },
  { id: 'l16-54', kanji: "バンドン", reading: "バンドン", meaning: "Bandung (Indonesia)", category: 'general', lesson: 16 },
  { id: 'l16-55', kanji: "フランケン", reading: "フランケン", meaning: "Franken (Đức)", category: 'general', lesson: 16 },
  { id: 'l16-56', kanji: "ベラクルス", reading: "ベラクルス", meaning: "Veracruz (Mexico)", category: 'general', lesson: 16 },
  { id: 'l16-57', kanji: "梅田", reading: "うめだ", meaning: "Tên một quận ở Osaka", category: 'kanji', lesson: 16 },
  { id: 'l16-58', kanji: "大学前", reading: "だいがくまえ", meaning: "Tên điểm dừng xe buýt giả định", category: 'kanji', lesson: 16 },

  // --- BÀI 17 ---
  { id: 'l17-1', kanji: "覚えます", reading: "おぼえます", meaning: "nhớ", category: 'verb', lesson: 17 },
  { id: 'l17-2', kanji: "忘れます", reading: "わすれます", meaning: "quên", category: 'verb', lesson: 17 },
  { id: 'l17-3', kanji: "なくします", reading: "なくします", meaning: "làm mất, đánh mất", category: 'verb', lesson: 17 },
  { id: 'l17-4', kanji: "払います", reading: "はらいます", meaning: "trả tiền", category: 'verb', lesson: 17 },
  { id: 'l17-5', kanji: "返します", reading: "かえします", meaning: "trả lại", category: 'verb', lesson: 17 },
  { id: 'l17-6', kanji: "出かけます", reading: "でかけます", meaning: "ra ngoài", category: 'verb', lesson: 17 },
  { id: 'l17-7', kanji: "脱ぎます", reading: "ぬぎます", meaning: "cởi (quần áo, giày, v.v.)", category: 'verb', lesson: 17 },
  { id: 'l17-8', kanji: "持って行きます", reading: "もっていきます", meaning: "mang đi, mang theo", category: 'verb', lesson: 17 },
  { id: 'l17-9', kanji: "持って来ます", reading: "もってきます", meaning: "mang đến", category: 'verb', lesson: 17 },
  { id: 'l17-10', kanji: "心配します", reading: "しんぱいします", meaning: "lo lắng", category: 'verb', lesson: 17 },
  { id: 'l17-11', kanji: "残業します", reading: "ざんぎょうします", meaning: "làm thêm giờ", category: 'verb', lesson: 17 },
  { id: 'l17-12', kanji: "出張します", reading: "しゅっちょうします", meaning: "đi công tác", category: 'verb', lesson: 17 },
  { id: 'l17-13', kanji: "飲みます [薬を～]", reading: "のみます", meaning: "uống [thuốc]", category: 'verb', lesson: 17 },
  { id: 'l17-14', kanji: "入ります [おふろに～]", reading: "はいります", meaning: "tắm bồn", category: 'verb', lesson: 17 },
  { id: 'l17-15', kanji: "大切 [な]", reading: "たいせつ", meaning: "quan trọng, quý giá", category: 'general', lesson: 17 },
  { id: 'l17-16', kanji: "大丈夫 [な]", reading: "だいじょうぶ", meaning: "không sao, không có vấn đề", category: 'general', lesson: 17 },
  { id: 'l17-17', kanji: "危ない", reading: "あぶない", meaning: "nguy hiểm", category: 'general', lesson: 17 },
  { id: 'l17-18', kanji: "禁煙", reading: "きんえん", meaning: "cấm hút thuốc", category: 'kanji', lesson: 17 },
  { id: 'l17-19', kanji: "[健康] 保険証", reading: "ほけんしょう", meaning: "thẻ bảo hiểm [y tế]", category: 'kanji', lesson: 17 },
  { id: 'l17-20', kanji: "熱", reading: "ねつ", meaning: "sốt", category: 'kanji', lesson: 17 },
  { id: 'l17-21', kanji: "病気", reading: "びょうき", meaning: "ốm, bệnh", category: 'kanji', lesson: 17 },
  { id: 'l17-22', kanji: "薬", reading: "くすり", meaning: "thuốc", category: 'kanji', lesson: 17 },
  { id: 'l17-23', kanji: "[お] ふろ", reading: "おふろ", meaning: "bồn tắm", category: 'general', lesson: 17 },
  { id: 'l17-24', kanji: "上着", reading: "うわぎ", meaning: "áo khoác", category: 'kanji', lesson: 17 },
  { id: 'l17-25', kanji: "下着", reading: "したぎ", meaning: "quần áo lót", category: 'kanji', lesson: 17 },
  { id: 'l17-26', kanji: "のど", reading: "のど", meaning: "họng", category: 'general', lesson: 17 },
  { id: 'l17-27', kanji: "かぜ", reading: "かぜ", meaning: "cảm, cúm", category: 'general', lesson: 17 },
  { id: 'l17-28', kanji: "２、3日", reading: "にさんにち", meaning: "2, 3 ngày/vài ngày", category: 'kanji', lesson: 17 },
  { id: 'l17-29', kanji: "～までに", reading: "までに", meaning: "trước ~, cho đến trước ~", category: 'general', lesson: 17 },
  { id: 'l17-30', kanji: "ですから", reading: "ですから", meaning: "vì thế, vì vậy, do đó", category: 'general', lesson: 17 },
  { id: 'l17-31', kanji: "どうしましたか", reading: "どうしましたか", meaning: "Có vấn đề gì?/Anh/Chị bị làm sao?", category: 'general', lesson: 17 },
  { id: 'l17-32', kanji: "[～が] 痛いです", reading: "いたいですか", meaning: "Tôi bị đau [~].", category: 'kanji', lesson: 17 },
  { id: 'l17-33', kanji: "お大事に", reading: "おだいじに", meaning: "Anh/Chị nhớ giữ gìn sức khỏe.", category: 'kanji', lesson: 17 },

  // --- BÀI 18 ---
  { id: 'l18-1', kanji: "できます", reading: "できます", meaning: "có thể", category: 'verb', lesson: 18 },
  { id: 'l18-2', kanji: "洗います", reading: "あらいます", meaning: "rửa", category: 'verb', lesson: 18 },
  { id: 'l18-3', kanji: "弾きます", reading: "ひきます", meaning: "chơi (nhạc cụ, pianô, v.v.)", category: 'verb', lesson: 18 },
  { id: 'l18-4', kanji: "歌います", reading: "うたいます", meaning: "hát", category: 'verb', lesson: 18 },
  { id: 'l18-5', kanji: "集めます", reading: "あつめます", meaning: "sưu tầm, thu thập, tập hợp", category: 'verb', lesson: 18 },
  { id: 'l18-6', kanji: "捨てます", reading: "すてます", meaning: "vứt, bỏ, bỏ đi", category: 'verb', lesson: 18 },
  { id: 'l18-7', kanji: "換えます", reading: "かえます", meaning: "đổi, trao đổi", category: 'verb', lesson: 18 },
  { id: 'l18-8', kanji: "運転します", reading: "うんてんします", meaning: "lái", category: 'verb', lesson: 18 },
  { id: 'l18-9', kanji: "予約します", reading: "よやくします", meaning: "đặt chỗ, đặt trước", category: 'verb', lesson: 18 },
  { id: 'l18-10', kanji: "ピアノ", reading: "ピアノ", meaning: "đàn piano", category: 'general', lesson: 18 },
  { id: 'l18-11', kanji: "～メートル", reading: "～めーとる", meaning: "～ mét", category: 'general', lesson: 18 },
  { id: 'l18-12', kanji: "現金", reading: "げんきん", meaning: "tiền mặt", category: 'kanji', lesson: 18 },
  { id: 'l18-13', kanji: "趣味", reading: "しゅみ", meaning: "sở thích, thú vui", category: 'kanji', lesson: 18 },
  { id: 'l18-14', kanji: "日記", reading: "にっき", meaning: "nhật ký", category: 'kanji', lesson: 18 },
  { id: 'l18-15', kanji: "お祈り", reading: "おいのり", meaning: "việc cầu nguyện", category: 'kanji', lesson: 18 },
  { id: 'l18-16', kanji: "動物", reading: "どうぶつ", meaning: "động vật", category: 'kanji', lesson: 18 },
  { id: 'l18-17', kanji: "馬", reading: "うま", meaning: "ngựa", category: 'kanji', lesson: 18 },
  { id: 'l18-18', kanji: "インターネット", reading: "インターネット", meaning: "In-tơ-nét, Internet", category: 'general', lesson: 18 },
  { id: 'l18-19', kanji: "課長", reading: "かちょう", meaning: "tổ trưởng", category: 'kanji', lesson: 18 },
  { id: 'l18-20', kanji: "部長", reading: "ぶちょう", meaning: "trưởng phòng", category: 'kanji', lesson: 18 },
  { id: 'l18-21', kanji: "社長", reading: "しゃちょう", meaning: "giám đốc", category: 'kanji', lesson: 18 },
  { id: 'l18-22', kanji: "特に", reading: "とくに", meaning: "đặc biệt là", category: 'kanji', lesson: 18 },
  { id: 'l18-23', kanji: "へえ", reading: "へえ", meaning: "Thế á!", category: 'general', lesson: 18 },
  { id: 'l18-24', kanji: "それは おもしろいですね", reading: "それはおもしろいですね", meaning: "(Cái đấy) hay thật nhỉ.", category: 'general', lesson: 18 },
  { id: 'l18-25', kanji: "なかなか", reading: "なかなか", meaning: "khó mà, mãi mà (dùng với thể phủ định)", category: 'general', lesson: 18 },
  { id: 'l18-26', kanji: "ほんとうですか", reading: "ほんとうですか", meaning: "Thật không ạ?", category: 'general', lesson: 18 },
  { id: 'l18-27', kanji: "ぜひ", reading: "ぜひ", meaning: "nhất định", category: 'general', lesson: 18 },
  { id: 'l18-28', kanji: "故郷", reading: "ふるさと", meaning: "Furusato (tên bài hát: \"Quê nhà\")", category: 'kanji', lesson: 18 },
  { id: 'l18-29', kanji: "ビートルズ", reading: "ビートルズ", meaning: "Beatles", category: 'general', lesson: 18 },
  { id: 'l18-30', kanji: "秋葉原", reading: "あきはばら", meaning: "Akihabara", category: 'kanji', lesson: 18 },

  // --- BÀI 19 ---
  { id: 'l19-1', kanji: "登ります [山に～]", reading: "のぼります", meaning: "leo [núi], lên", category: 'verb', lesson: 19 },
  { id: 'l19-2', kanji: "泊まります [ホテルに～]", reading: "とまります", meaning: "trọ [ở khách sạn]", category: 'verb', lesson: 19 },
  { id: 'l19-3', kanji: "掃除します", reading: "そうじします", meaning: "dọn vệ sinh (căn phòng)", category: 'verb', lesson: 19 },
  { id: 'l19-4', kanji: "洗濯します", reading: "せんたくします", meaning: "giặt (quần áo)", category: 'verb', lesson: 19 },
  { id: 'l19-5', kanji: "なります", reading: "なります", meaning: "trở thành, trở nên", category: 'verb', lesson: 19 },
  { id: 'l19-6', kanji: "眠い", reading: "ねむい", meaning: "buồn ngủ", category: 'general', lesson: 19 },
  { id: 'l19-7', kanji: "強い", reading: "つよい", meaning: "mạnh", category: 'general', lesson: 19 },
  { id: 'l19-8', kanji: "弱い", reading: "よわい", meaning: "yếu", category: 'general', lesson: 19 },
  { id: 'l19-9', kanji: "練習", reading: "れんしゅう", meaning: "sự luyện tập", category: 'kanji', lesson: 19 },
  { id: 'l19-10', kanji: "ゴルフ", reading: "ゴルフ", meaning: "gôn (golf)", category: 'general', lesson: 19 },
  { id: 'l19-11', kanji: "相撲", reading: "すもう", meaning: "môn vật Sumo", category: 'kanji', lesson: 19 },
  { id: 'l19-12', kanji: "お茶", reading: "おちゃ", meaning: "trà đạo", category: 'kanji', lesson: 19 },
  { id: 'l19-13', kanji: "日", reading: "ひ", meaning: "ngày", category: 'kanji', lesson: 19 },
  { id: 'l19-14', kanji: "調子", reading: "ちょうし", meaning: "tình trạng, trạng thái", category: 'kanji', lesson: 19 },
  { id: 'l19-15', kanji: "一度", reading: "いちど", meaning: "một lần", category: 'kanji', lesson: 19 },
  { id: 'l19-16', kanji: "一度も", reading: "いちども", meaning: "chưa lần nào, chưa bao giờ (dùng với phủ định)", category: 'kanji', lesson: 19 },
  { id: 'l19-17', kanji: "だんだん", reading: "だんだん", meaning: "dần dần", category: 'general', lesson: 19 },
  { id: 'l19-18', kanji: "もうすぐ", reading: "もうすぐ", meaning: "sắp, sắp sửa", category: 'general', lesson: 19 },
  { id: 'l19-19', kanji: "おかげさまで", reading: "おかげさまで", meaning: "Cám ơn anh/chị, nhờ anh/chị mà ～", category: 'general', lesson: 19 },
  { id: 'l19-20', kanji: "でも", reading: "でも", meaning: "nhưng", category: 'general', lesson: 19 },
  { id: 'l19-21', kanji: "乾杯", reading: "かんぱい", meaning: "Cạn chén! / Nâng cốc!", category: 'kanji', lesson: 19 },
  { id: 'l19-22', kanji: "ダイエット", reading: "ダイエット", meaning: "việc ăn kiêng, chế độ giảm cân", category: 'general', lesson: 19 },
  { id: 'l19-23', kanji: "無理 [な]", reading: "むり", meaning: "không thể, quá sức", category: 'general', lesson: 19 },
  { id: 'l19-24', kanji: "体にいい", reading: "からだにいい", meaning: "tốt cho sức khỏe", category: 'general', lesson: 19 },
  { id: 'l19-25', kanji: "東京スカイツリー", reading: "東京スカイツリー", meaning: "Tokyo Sky Tree (tháp truyền hình)", category: 'general', lesson: 19 },
  { id: 'l19-26', kanji: "葛飾北斎", reading: "かつしかほくさい", meaning: "Katsushika Hokusai (họa sĩ nổi tiếng)", category: 'kanji', lesson: 19 },

  // --- BÀI 20 ---
  { id: 'l20-1', kanji: "要ります [ビザが～]", reading: "いります", meaning: "cần [thị thực/visa]", category: 'verb', lesson: 20 },
  { id: 'l20-2', kanji: "調べます", reading: "しらべます", meaning: "tìm hiểu, kiểm tra, điều tra", category: 'verb', lesson: 20 },
  { id: 'l20-3', kanji: "修理します", reading: "しゅうりします", meaning: "sửa chữa, tu sửa", category: 'verb', lesson: 20 },
  { id: 'l20-4', kanji: "僕", reading: "ぼく", meaning: "tôi, tớ (nam giới)", category: 'general', lesson: 20 },
  { id: 'l20-5', kanji: "君", reading: "きみ", meaning: "cậu, bạn (ngang hàng/ít tuổi)", category: 'general', lesson: 20 },
  { id: 'l20-6', kanji: "～君", reading: "～くん", meaning: "anh, cậu (thân mật cho nam)", category: 'general', lesson: 20 },
  { id: 'l20-7', kanji: "うん", reading: "うん", meaning: "ừ (thân mật của \"hai\")", category: 'general', lesson: 20 },
  { id: 'l20-8', kanji: "ううん", reading: "ううん", meaning: "không (thân mật của \"iie\")", category: 'general', lesson: 20 },
  { id: 'l20-9', kanji: "ことば", reading: "ことば", meaning: "từ, tiếng", category: 'general', lesson: 20 },
  { id: 'l20-10', kanji: "着物", reading: "きもの", meaning: "kimono", category: 'general', lesson: 20 },
  { id: 'l20-11', kanji: "ビザ", reading: "ビザ", meaning: "thị thực, visa", category: 'general', lesson: 20 },
  { id: 'l20-12', kanji: "初め", reading: "はじめ", meaning: "ban đầu, đầu tiên", category: 'general', lesson: 20 },
  { id: 'l20-13', kanji: "終わり", reading: "おわり", meaning: "kết thúc, hết", category: 'general', lesson: 20 },
  { id: 'l20-14', kanji: "こっち", reading: "こっち", meaning: "phía này, chỗ này (thân mật \"kochira\")", category: 'general', lesson: 20 },
  { id: 'l20-15', kanji: "そっち", reading: "そっち", meaning: "phía đó, chỗ đó (thân mật \"sochira\")", category: 'general', lesson: 20 },
  { id: 'l20-16', kanji: "あっち", reading: "あっち", meaning: "phía kia, chỗ kia (thân mật \"achira\")", category: 'general', lesson: 20 },
  { id: 'l20-17', kanji: "どっち", reading: "どっち", meaning: "cái nào, phía nào, đâu (thân mật \"dochira\")", category: 'general', lesson: 20 },
  { id: 'l20-18', kanji: "みんなで", reading: "みんなで", meaning: "mọi người cùng", category: 'general', lesson: 20 },
  { id: 'l20-19', kanji: "～けど", reading: "～けど", meaning: "~, nhưng (thân mật của \"ga\")", category: 'general', lesson: 20 },
  { id: 'l20-20', kanji: "おなかが いっぱい", reading: "おなかが いっぱい", meaning: "(Tôi) no rồi", category: 'general', lesson: 20 },
  { id: 'l20-21', kanji: "よかったら", reading: "よかったら", meaning: "nếu anh/chị thích thì", category: 'general', lesson: 20 },
  { id: 'l20-22', kanji: "いろいろ", reading: "いろいろ", meaning: "nhiều thứ", category: 'general', lesson: 20 }
];

export const SYSTEM_PROMPT = `Bạn là một giáo viên tiếng Nhật chuyên gia, hỗ trợ học sinh luyện thi JLPT N5 dựa trên giáo trình Minna no Nihongo. 
Khi giải thích một từ vựng:
1. Giải thích ý nghĩa rõ ràng theo đúng ngữ cảnh sơ cấp.
2. Cung cấp ví dụ thực tế đơn giản phù hợp trình độ N5.
3. Giải thích cách dùng trong ngữ cảnh văn hóa Nhật Bản.
4. Trả lời bằng tiếng Việt thân thiện.
5. Nếu là động từ, hãy nhắc đến nhóm động từ (1, 2, 3).`;
